### ISSUE TITLE
Clone TI button layout

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#1]
Hi Team,

In the Clone process popup window, the Save button should be replaced with Clone and the icon in the pop up is different than the one on the button:
![image](https://user-images.githubusercontent.com/25290041/37639062-16059e80-2c64-11e8-8ac3-6d32fcea8487.png)

The order of the buttons should be first, Cancel and then Clone to keep it consistent with the other popup windows.

**Comment by cubewise-tryan** [comment]
Hi @vviau,

The icon and titles have been changed to **Clone**, it will be in the next release.
