### ISSUE TITLE
Auto complete of CellGets inserts Sandbox dimension.

### ISSUE THREAD

**Issue by 4rtem** [cubewise-code/arc-issues#101]
Hi guys,
Sandbox dimension is mentioned in the auto completion text for CellGetS. We have enabled sandbox as the dimension to be used in PAW, but we do not need to mention that in the rule.
Thanks.
v0.9.7

![image](https://user-images.githubusercontent.com/37865391/40350154-2b7cefc2-5da9-11e8-91bb-15de2d210130.png)

**Comment by cubewise-tryan** [comment]
Hi @4rtem,

I don't think that is a bug, Arc just receives the list of the dimensions from TM1 and because you have enabled the virtual sandbox dimension it is included.

**Comment by 4rtem** [comment]
Tm1 does not expect sandboxes dimension to be mentioned in the Rule or TI
![image](https://user-images.githubusercontent.com/37865391/40645079-8cdd8a7a-6325-11e8-9e04-ed2432455e3f.png)

**Comment by 4rtem** [comment]
Hi Tim, 
Rule does not work if you insert !sandboxes into CellGetS in TI or DB in the rule. 
It should should not be inserted by autocompletion.

**Comment by 4rtem** [comment]
Hi @cubewise-tryan .
Any progress/response on that?
Probably not a lot of people  enabled sandbox dimension, did you/guys guys tried to do this?
