### ISSUE TITLE
Hierarchy editor: tab caption doesn't update

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#107]
Arc 0.9.7 

When the hierarchy editor is opened by clicking on a hierarchy under a dimension the new tab is captioned with instance:hierarchy.

If the selected hierarchy is subsequently changed via the hierarchy selector dropdown the tab caption does not update. Updates are correctly recorded according to the hierarchy selected in the dropdown and not the caption, hence this is only a display issue.

When opening the hierarchy editor from the default hierarchy named the same as the dimension this issue goes unnoticed as it seems quite logical for the tab to be captioned instance:dimension (as opposed to instance:hierarchy) as really there isn't any need to change the tab caption on selection of a hierarchy.

Possible solution: just always caption the tab instance:dimension regardless which hierarchy the editor is launched from.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram ,

This one is a little tricky as we needed to create a unique URL for each hierarchy so you can have more than one hierarchy open at the same time. It is possible to have the dimension name only but then you wouldn't be able to know which hierarchy is open in which tab.
