### ISSUE TITLE
Add standard extended edit options for cube & dimension objects

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#11]
Arc 0.9.2
In architect/perspectives there are some context menu shortcuts to make creating or editing control object extensions of a "base object" easier to access. Currently these options aren't available in Arc and creating of objects like picklist cube and drill assignment needs to be done in architect.

For cubes add options to
- create/edit picklist cube
- create/edit drill assignment rules
- create/edit drill process
- create/edit cell security cube
- edit cube attributes
- edit cube properties

For dimensions add options to
- create/edit element security
- edit dimension attributes
- edit dimension properties

**Comment by cubewise-tryan** [comment]
Hi @lotsaram ,

Each should be separated into individual issues, at least by functionality, i.e. drill through, security, etc. Many of them require a cube editor that will be coming as part of the 1.0 release.
