### ISSUE TITLE
[Bug] Missing dimensions in cube viewer - Firefox

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#110]
Hello,

In Firefox 60.0.1 the cube viewer doesn't display any dimensions. This happens for both new or existing views.
Arc version 0.9.7
TM1 version 11.1.00000.30

Screen shots:
New view:
![image](https://user-images.githubusercontent.com/39726565/40650446-3b121c6e-632b-11e8-8b68-513a2cdfad21.png)

Existing view:
![image](https://user-images.githubusercontent.com/39726565/40650490-552c8efe-632b-11e8-8255-6c93eaedb7f5.png)

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor,

Can you please test this with 0.9.8 when it comes out as this is working for me but we have also fixed some other bugs in Firefox/IE.

**Comment by RaduCantor** [comment]
Hi @cubewise-tryan 
This issue is fixed. However there are other parts of the cube viewer which got broken (in all browsers).
I will open a separate issue ticket for that.
