### ISSUE TITLE
Commented lines containing If( have folding applied

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#114]
Arc 0.9.7, rule editor
Chrome

If a commented line contains IF( anywhere in the line then folding is applied. 
![image](https://user-images.githubusercontent.com/29408388/40790771-11462dfe-64f6-11e8-9dc0-84b3624e3971.png)

![image](https://user-images.githubusercontent.com/29408388/40790791-2260fbbe-64f6-11e8-81cd-71df48e06c72.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram ,

I the development version I am using I can't repeat this issue. Can you please test it when 0.9.8 comes out.

**Comment by lotsaram** [comment]
I just tested again in 1.0 and it seems solved. Pure comments no longer folding where if present in the line.
![image](https://user-images.githubusercontent.com/29408388/44334999-5c356e80-a473-11e8-9135-0e3821473f3a.png)

But for code that is commented. Or comments that look enough like code then folding logic is still applied to lines starting with #
![image](https://user-images.githubusercontent.com/29408388/44335183-f4335800-a473-11e8-8eb7-a07f3d5f49a0.png)

Which for me is fine. I guess this is more of a feature design issue. Should commenting preclude folding or should commented code still be foldable?
