### ISSUE TITLE
Unable to connect to newly created ODBC data source - works in Architect.

### ISSUE THREAD

**Issue by dwigsy** [cubewise-code/arc-issues#115]
We have had a new ODBC datasource added. I have restarted Arc 0.9.7 and can view the process but cannot preview the datasource. 
![arcodbc_connectissue](https://user-images.githubusercontent.com/39814816/40815698-9808539a-658b-11e8-9d46-0e8ea5b01ac2.JPG)

**Comment by dwigsy** [comment]
I have just realised that the ODBC connections may not be visible to ARC for previewing purposes but that the process will execute.

**Comment by cubewise-tryan** [comment]
As discussed offline to preview an ODBC data source (or text) you need to install Arc on the TM1 server or add the ODBC DSNs to where Arc is installed.
