### ISSUE TITLE
ER: run TI processes asynchronously 

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#117]
Arc 0.9.7

In Arc it is a really nice feature that as a developer you can save a rule or run a TI process and continue to work without it  blocking your session in Arc.

However in the background the activities are still queuing under a single user. It would be a really nice enhancement if Arc would open an independent thread on the server and allow such actions to be done in parallel rather than a serial job queue.

![image](https://user-images.githubusercontent.com/29408388/40846624-6a62015a-65ba-11e8-9bfe-123820cd3b65.png)
![image](https://user-images.githubusercontent.com/29408388/40846633-6f56ac10-65ba-11e8-8d3f-da1f834ff275.png)

**Comment by cubewise-tryan** [comment]
We don't have control over this, the browser manages the sessions/cookies for the REST API.
