### ISSUE TITLE
TI and rule editor fast scroll stuttering

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#118]
When you first open the TI or rule editor and you want to fast scroll to the button of page, the scroll stutters and stops. Basically it won't scroll smoothly to the bottom. This is particularly annoying because you need to keep scrolling in order to get to the lower section of the code in rules or TIs, especially when there are hundreds or thousand of lines of code.
In the earlier versions of Arc this didn't happen.

Arc version 0.9.7
TM1 version 11.1.00000.30

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor ,

Are you talking about the editor window? That is a third-party control so there isn't a lot we can do to fix it.

**Comment by RaduCantor** [comment]
Hi @cubewise-tryan 

Yes, I'm referring to the editor window. However I did more testing and apparently it happens only on Firefox. For other browsers is working perfectly fine (Chrome or Opera), or better (Edge).

When using Firefox and fast scrolling inside the editor window, the scroll just freezes. So you either have to scroll slowly, or use the scroll bar.
When using Edge or IE, the fast scroll stutters, but at least it scrolls to the bottom of the page and doesn't freeze in the middle.

Could it be, because of the following warning (in Firefox)?

![image](https://user-images.githubusercontent.com/39726565/41847116-398e55fc-7879-11e8-9a66-3a4a446d4574.png)

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor ,

I don't think that is related. I think it might just be an issue with Firefox. I have tested it out and there is a little bit of lag, there isn't a lot we can do about it as we use a third party library.
