### ISSUE TITLE
Create process does not add new process to recent objects list

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#119]
Arc 0.9.7

If a new process is created via SaveAs then both the old process and new process get listed in the recent objects. but if a completely blank new process is created then the new object isn't listed in the recents list.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram ,

It is a little complicated to fix this one because at the time the "last used" list gets updated the new process hasn't been add to the menu so there is nothing to add. We are going to change how the menu works so it may get fix amongst those changes.
