### ISSUE TITLE
Minor: LogOutput is not recognized as function by code colorizer

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#12]
Arc 0.9.2
LogOutput is not recognized as a function keyword by the editor themes for code colorization and appears formatted the same as variables.
![image](https://user-images.githubusercontent.com/29408388/37772204-372cf4c4-2dda-11e8-9314-833b6b6ff032.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram, this was added yesterday so it will be in the next release.
