### ISSUE TITLE
Code folding broken in TI editor

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#122]
Arc 0.9.7
Chrome

In 0.9.7 code folding in the TI editor is not working at all.
If/EndIf, While/End, Region/EndRegion all display the folding arrow button but clicking on the button doesn't do anything.

**Comment by psegal** [comment]
I'm getting the same issue in Firefox, Arc 0.9.7. (also IE11).

**Comment by cubewise-tryan** [comment]
#60
