### ISSUE TITLE
Create cube: overwrite if already existing

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#123]
Arc 0.9.7

When using the create new cube function if an object of the same name already exists then Arc returns an error message "A cube named xxxxx already exists." and the cube is not recreated.

Desired functionality same as perspectives/architect: if an object of the same name already exists then Arc should prompt "A cube named xxxxx already exists. Do you want to recreate the cube?" With Yes/No options.

Currently  the user needs to exit the create cube dialog, delete the cube and then go back and make selections in the create cube dialog again. Also as the delete cube option is currently integrated with the rule editor then it is necessary to save a copy of the rule manually to another text editor. It would be much more convenient in circumstances of recreating a cube to have the rule editor tab open, then recreate the cube then re-save the rule. Without having to do additional workaround steps.

**Comment by rclapp** [comment]
I agree and would also add that the cube builder should be a tab just like everything else. That way users can continue to browse the model while building the cube.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

This is possible but a low priority at the moment. There are lots of other things we have do before changing this behaviour.

**Comment by cubewise-tryan** [comment]
Hi @rclapp, 

We don't have plans to add the cube creator as a tab it would be complicated to implement.
