### ISSUE TITLE
Hyperlinks does not open new tab

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#125]
Hi,

Arc v0.9.7, when using hyperlinks to any TM1 objects, Arc does not open a new tab.

For instance, the following code does not open a new tab:
`<a href="#/cube/view/Canvas%20Sample/General%20Ledger/Default" ng-click="user_clicks_branch(row.branch)" ng-class="[row.branch.item_class]">
                                Default view
                            </a>`
Actually, the code above will work only if the tab has been opened before.

Cheers,

Vincent

**Comment by cubewise-tryan** [comment]
Hi @vviau,

Are you sure? I have tested it with cubes and dimensions and they open OK with a hyperlink.

**Comment by vviau** [comment]
Hi @cubewise-tryan ,

I think the issue is only with subsets and views, opening a TI, a rule and a chore is working.

When trying to open a view or a subset, the hyperlink will work only if the view or the subset has been opened previously.

Cheers,

Vincent
