### ISSUE TITLE
Cube Viewer behavior

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#129]
Hello,

In the latest Arc version the cube viewer has a number of bugs.

Arc version 0.9.8
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

1. None of the input cells in Arc are editable. You cannot write any value, numeric or string. Picklists are working fine, but normal input cells aren't. (please see attached images).
2. Picklists that contain duplicates throw an error and are not loaded (please see attached images).
3. There is no way to delete a value from a cell with a picklist.
4. Saving a new view doesn't automatically refresh the view list for the cube. Also it would be nice to have only the list of views for that particular cube refreshed, rather than the whole tree. I noticed that if I save a new subset it refreshes the entire object tree, which is quite slow.
5. The column headers could get misaligned if the value selected in the picklist is larger than the header (please see attached images).
6. The calculated and consolidated values are showing fine and the text is with a different color. However there is no way to differentiate between a calculated empty cell and an input empty cell.
7. (this one is related to dimension editor). If I try to create a new hierarchy I get "New hierarchy creation is disabled". Is this happening because of Arc functionality, or am I missing some configuration in TM1?

**Arc cube viewer**
![arc 0 98 cubeviewer](https://user-images.githubusercontent.com/39726565/41844578-e61b3a78-7870-11e8-964f-29c09f49acda.PNG)

**Architect (same view)**
![architect view](https://user-images.githubusercontent.com/39726565/41844598-f19ad28c-7870-11e8-8df9-12bdff0c37a4.PNG)

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor ,

Thanks for the great feedback, we need the different issues in separate tickets so we can track and update them as they are fixed.
