### ISSUE TITLE
Copy/Paste Elements between two hierarchies

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#131]
Hi,

Arc v0.9.8 and PAL 2.0.3

The Paste button is missing if you change hierarchy:

The Copy/Paste buttons work when you are in the same hierarchy:
![image](https://user-images.githubusercontent.com/25290041/41888625-fb23261a-7938-11e8-9583-b0b3bdbb5a04.png)

What I would like to do is copy the element "6" from the "Department" hierarchy and paste it in my new Hierarchy "Type". So I copy first the element and then when I change the hierarchy to "Type", I can't see the paste button:

1. Click copy button from the Department hierarchy:
![image](https://user-images.githubusercontent.com/25290041/41888715-75d79e54-7939-11e8-8a4d-ca32f092ad26.png)

2. Change the hierarchy to "Type" and there is no paste button
![image](https://user-images.githubusercontent.com/25290041/41888755-988245b2-7939-11e8-86ab-8fe1ed57e4e3.png)

Cheers,

Vincent

**Comment by cubewise-tryan** [comment]
Hi @vviau,

This one is easy said than done so we don't plan to add it. For elements that exist in the another hierarchy you can add them with the + button.
