### ISSUE TITLE
Subset Editor - Refresh button not working

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#134]
Hi,

Arc v0.9.8, PAL 2.0.3

When I click on the refresh button, nothing happens.

I opened an existing subset, use some options like filter by level but then I wanted to reload the subset to go back to the start so I clicked the refresh button but nothing happens:
![image](https://user-images.githubusercontent.com/25290041/41895015-70ce72ec-7953-11e8-94f6-1ec6ff830613.png)

The expecting behavior would be the same as the "Reload" button in Architect, when you click on it, it reset the list of elements:
![image](https://user-images.githubusercontent.com/25290041/41895074-9c6084ea-7953-11e8-9005-544787cbb1cb.png)

Cheers,

Vincent

**Comment by cubewise-tryan** [comment]
Hi @vviau,

The refresh button in the subset editor refreshes the content based current expression, it doesn't reset it. You will need to close or select a different subset to reset it.
