### ISSUE TITLE
Cube viewer header misalignment when the values are too big / long

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#137]
Arc version 0.9.8
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

The column headers could get misaligned if the value selected in the picklist is larger than the header (please see attached images).

**Arc cube viewer**
![arc 0 98 cubeviewer](https://user-images.githubusercontent.com/39726565/41844578-e61b3a78-7870-11e8-964f-29c09f49acda.PNG)

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor ,

Try this on the 0.9.9 when it comes out as we have changed how the editor works in the cube viewer.
