### ISSUE TITLE
Different background for calculated or consolidated cells

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#138]
Arc version 0.9.8
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

The calculated and consolidated values are showing fine and the text is with a different color. However there is no way to differentiate between a calculated empty cell and an input empty cell.
It would be nice to have a different background to the calculated or consolidated cells, similar to Architect.

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor ,

We will look at this when we add rule tracing, I will close this issue and as we already have a ticket open: #83
