### ISSUE TITLE
Cannot create a new hierarchy

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#139]
Arc version 0.9.8
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

If I try to create a new hierarchy I get "New hierarchy creation is disabled". 

![image](https://user-images.githubusercontent.com/39726565/41895647-e10a0b6a-7922-11e8-9890-15c10fd383d0.png)

**Comment by lotsaram** [comment]
This isn't an Arc issue. You need to have EnableNewHierarchyCreation=T in tm1s.cfg
This is set to False by default, don't know why.
