### ISSUE TITLE
Arc Chore-Activity handling

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/arc-issues#14]
Currently when a chore is activated Arc will not be able to edit its properties.

Feature Request:
I would like Arc to handle the Activation / Deactivation under the hood. 
If I change the start time of a chore, I would like Arc to first deactivate the Chore, then send my update to TM1, and then reactivate the chore again.

Is that possible?

**Comment by cubewise-tryan** [comment]
Hi @MariusWirtz , that wouldn't be too difficult, we will add it to the next release.

**Comment by cubewise-tryan** [comment]
In the up coming 0.9.3 release
