### ISSUE TITLE
Execution Dialog Box of non-parameterized TI serves no purpose

### ISSUE THREAD

**Issue by uttergithub** [cubewise-code/arc-issues#140]
Arc 0.98

When a TI has no params, execution dialog box serves no purpose.

![2018-06-27 09_26_20-arc for tm1](https://user-images.githubusercontent.com/37645851/41944781-eb8a10ec-79ec-11e8-8076-6e45bb5185b9.png)

**Comment by cubewise-tryan** [comment]
Hi @uttergithub,

It provides a "confirm" dialog and keeps it consist with processes with parameters.
