### ISSUE TITLE
UI: Cubeviewer Toolbar unclear whether functionality is on or off

### ISSUE THREAD

**Issue by uttergithub** [cubewise-code/arc-issues#141]
Arc 0.98

Buttons for Show/Hide Hierarchies, AutoCalc and Row/Col Suppress Zeros are either grey or greyer. Not intuitive as to whether they are on or off.

![2018-06-27 09_38_01-arc for tm1](https://user-images.githubusercontent.com/37645851/41944991-2757a084-79ee-11e8-9a0c-dd589665d39c.png)

**Comment by cubewise-tryan** [comment]
Hi @uttergithub ,

The shading can be a little hard to see but you can see that the shade is different to the MDX button. Once you get used to it I think it is clear enough.
