### ISSUE TITLE
TI and Rule Editor Shortcuts

### ISSUE THREAD

**Issue by uttergithub** [cubewise-code/arc-issues#142]
Arc 0.98

Could we have a button that shows a modal popup with all the shortcut tips and tricks?

Summarising something like this;

https://www.cheatography.com/bipinthite/cheat-sheets/ace-editor/

**Comment by lotsaram** [comment]
+1

**Comment by cubewise-tryan** [comment]
Hi @uttergithub,

We now have a help page for this: https://code.cubewise.com/arc-docs/arc-shortcut-keys
