### ISSUE TITLE
Arc View Definition

### ISSUE THREAD

**Issue by cubewise-plim** [cubewise-code/arc-issues#143]
Arc: 0.9.8

When saving an Arc View, the previous elements are still in the Arc View definition text. 

Changing a title dimension to use another subset for example, does not seem to update the Arc View definition.

Sample screenshot of the text view on a Cube using a Version dimension for example, that was supposed to be using a subset:

![image](https://user-images.githubusercontent.com/22946355/41948795-c87f0a70-7a01-11e8-8486-6873d9f87daa.png)

The 'Baddes' for example is part of the Version dimension that I am using - though I had changed to use only a subset. The dropdown for that Version dimension is showing exactly what is in the subset:

![image](https://user-images.githubusercontent.com/22946355/41948840-0dc04176-7a02-11e8-8613-9126d2f596c0.png)

But the view text still retains the previous elements (i.e. Baddes).

**Comment by cubewise-tryan** [comment]
Hi @cubewise-plim ,

This has been updated, can you please confirm it is being updated correctly.

**Comment by cubewise-plim** [comment]
Just to update and to confirm that this has been fixed. 

Thanks!
