### ISSUE TITLE
Wrong Error Message when updating Active Chore

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/arc-issues#15]
when I try to update an active Chore in Arc, Arc gives me the following ErrorMessage:
![errormsg](https://user-images.githubusercontent.com/15182131/37783008-a63ba378-2df4-11e8-8326-029608866513.png)

It should say something like, "Can't update active Chores" I suppose.

**Comment by cubewise-tryan** [comment]
Hi @MariusWirtz, 

That message is returned by the REST API so it would need to be changed by IBM. This would be fixed by your other ticket #14. I will close this one.
