### ISSUE TITLE
TI Error message issue

### ISSUE THREAD

**Issue by kmurphy111** [cubewise-code/arc-issues#153]
ARC 0.9.7
TM1 Planning Analytics 11.3.00000.27
Browser IE 11.431.16299

If i run a process which has minor errors i don't get any indication of the errors in arc. i get a green message which says process completed successfully. However the process may have produced an error log. If i run the same process in TM1 TI editor i get notified of minor errors. The process error notification only seems to work for me in arc if i have a major error that causes a process to abort.

Process run in arc
![run process in arc](https://user-images.githubusercontent.com/41028072/42484095-87aefb94-8434-11e8-9bfa-356c011157ce.JPG)
Process run in TM1
![same process run in tm1](https://user-images.githubusercontent.com/41028072/42484197-22828bb8-8435-11e8-939a-0e61c3d18dc3.JPG)

Both runs produce a error log:
![error logs in both runs](https://user-images.githubusercontent.com/41028072/42484317-afee4352-8435-11e8-80e6-d6e8c3ab1292.JPG)

**Comment by cubewise-tryan** [comment]
Hi @kmurphy111,

We will look in to that one, you will normally receive information about the error. It is possibly related to the version of TM1 you are using as there have been some changes to the REST API.

**Comment by cubewise-tryan** [comment]
Hi @kmurphy111, 

I have checked and the latest version of TM1 (2.0.5/11.3) has changed the response received when executing a process. We will look at what we can do to support that latest version.

**Comment by cubewise-tryan** [comment]
Hi @kmurphy111,

An update to this one. There is a bug in TM1 11.3 (2.0.5) that results in the server crashing when using the new action so we won't be able to implement it until the next release of TM1. 

You can continue to use the current version but you won't be notified of minor errors, for major errors you will still get the same result.

**Comment by kmurphy111** [comment]
OK thank you.

**Comment by cubewise-tryan** [comment]
The is an interim fix for 2.0.5 coming soon. We have fixed the processing handling so if you install the IF Arc should work as expected.
