### ISSUE TITLE
TI: Datasource of None still allows entry into MetaData and Data

### ISSUE THREAD

**Issue by lbrowncubewise** [cubewise-code/arc-issues#157]
When using TI in Architect with a datasource of None selected the Metadata and Data tabs are locked out stopping user entry, the same is not present in Arc. 
I have tested this and what happens is when the TI runs any code a user enters into the Metadata or Data tabs will be ignored as the process runs from Prolog and then jumps straight to the Epilog.

This could cause a potential confusion for developers, as the tabs are all available they will automatically code into the Metadata and Data tabs and then wonder why their processes are not working correctly when it comes to running them?

**Comment by lotsaram** [comment]
I don't see this as an issue. It is up to the TM1 developer to know that code on metadata and data tabs is only executed for processes with a data source (AND that the code is executed for each record of the data source, AND that the metadata and data query executions are separate and the records are not cached by TM1.)

**Comment by cubewise-tryan** [comment]
Hi @lbrowncubewise,

I agree with @lotsaram, I found it annoying that the metadata and data tabs were locked (even though there might be code there) in Architect. TM1 developers need to know when and how these tabs are used.
