### ISSUE TITLE
Too many chore names in Confirmation Message

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/arc-issues#16]
Hi,

I just had a situation in the chores Editor, where, when I wanted to execute an action, it always listed two items instead of one in the Confirmation Message.
The pattern seemed to be that, additionally to the currently selected one, it always listed the previously selected chore.
If I unchecked and checked a chore twice, it would show up double in the ConfirmationMessage:

![errormsg](https://user-images.githubusercontent.com/15182131/37784254-9fc9790e-2df7-11e8-95fc-981ca996e624.png)

When I closed and reopened the tab, the issue disappeared.

**Comment by cubewise-tryan** [comment]
Hi @MariusWirtz , 

Version of Arc and steps to reproduce?

**Comment by MariusWirtz** [comment]
Version: 0.9.2

Can be reroduced by playing around on the chores page:
- Open chores pages.
- click on individual chores (and jump to the chore editor), try to save them
- switch back to chores page
- select All, deselect all
- select many
- deselect many
- close chores page
- reopen chores page
- select stuff
- click Activate button

Hope it helps. I was able to reproduce the issue twice with these rough steps.

**Comment by cubewise-tryan** [comment]
Fixed in next release.
