### ISSUE TITLE
ER: Grid control in TI editor parameter and variables tabs

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#167]
Arc 0.9.9

It would be a great productivity gain if the parameter and variables tabs in the TI editor were implemented with a grid control to enable copy/paste to multiple cells at a time and tabbing / arrow key navigation within the parameters or variables table and column resizing.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

We don't have plans to change it to a grid control but what we have updated it so that the delete and up/down buttons are no longer part of the tab index. This means when pressing the tab key it will jump between input boxes. Use SHIFT+TAB to go backwards.
