### ISSUE TITLE
Use Top/Skip function to speed up TI View preview

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/arc-issues#169]
When previewing a view in the TI editor it appears the Arc executes the entire view and then displays only the number of rows requested via the preview control option. It would be much more efficient to appley the preview row number control value to the $top query option. When using very large leaf level views it can take a very long time for the results to return

**Comment by cubewise-tryan** [comment]
Hi @rclapp,

I have looked at the code and we already use the $top to limit the rows. What version of Arc are you using?

**Comment by rclapp** [comment]
I have the latest public release, .97. It seems that the time to preview large  native views is much slower than I would expect. If the view is large enough it results in an Out of Memory error (I think due to the view size)

**Comment by cubewise-tryan** [comment]
Hi @rclapp,

When you say an Out of Memory error is that the message or does the browser have an issue? We limit both the cells and tuples returned via the view to 10 (default).

**Comment by rclapp** [comment]
Interesting. This is how to recreate the issue. Take a large cube and create an "empty" native view. (Right click export text data, save with default options and "All" subsets). In Arc set that view as a data source and click preview. After some time you get out of memory error in the server log

22676   [5]   WARN   2018-08-10 14:44:10.324   TM1.Server.Memory   al_Alloc() outOfMemory Exception <<< MEMORY_TEMP_POOL_EXCEEDED >>> MaximumViewSize memory exceeded - apifunc# "0" - pool# "0" - poolsize "26222772992.000000"
and the attached in Arc.

This could be a C API vs REST API issue. Since the same view quickly returns a few records in architect. When i watch the preview that architect runs it seems to be using CubeCellValueGet, which would not require the entire view be executed.

![memory error](https://user-images.githubusercontent.com/18215782/43982896-d865fe9e-9cac-11e8-9744-ccebab5e88be.png)

**Comment by cubewise-tryan** [comment]
Hi @rclapp,

I have talked to IBM about it and this is a TM1 server issue, the $top filter only filters _AFTER_ the view has been executed on the server. That is why you get the out of memory error.
