### ISSUE TITLE
Documentation: Getting Started.pdf api/v1/Servers vs api/v1/Server

### ISSUE THREAD

**Issue by strangiato** [cubewise-code/arc-issues#17]
In the Getting Started PDF file, under step 6 of "Running the Arc executable", the documentation refers to https://servername:5898/api/v1/Servers but it should refer to https://servername:5898:api/v1/Server without the s at the end.

**Comment by cubewise-tryan** [comment]
Hi @strangiato, **Servers** is correct resource for the REST API on the admin host, **Server** is part of REST API for a TM1 instance. You get a response like this from Servers (https://localhost:5898/api/v1/Servers):

![image](https://user-images.githubusercontent.com/22929868/37796994-b73d29bc-2e6c-11e8-9c30-fa8d8f79d12e.png)

**Comment by strangiato** [comment]
Thanks for the update tryan!

This actually helped me resolve the issue I ran into trying to get Arc working.  I was attempting to point my settings.yml file at my TM1 instances API instead of the admin host API.

Rereading the documentation now, it does obviously say that it is the Admin Host, but I was thinking it needed to point to the instances API since a few section before that it talks about enabling the API.

It might help to add something to mention that it is the Admin Host API so others might avoid my same issue.

Thanks for the help though.

The tool looks really great and I am looking forward to seeing what you guys are going to do with it moving forward!
