### ISSUE TITLE
Error when preview subset

### ISSUE THREAD

**Issue by kmurphy111** [cubewise-code/arc-issues#172]
ARC 0.9.7
TM1 Planning Analytics 11.3.00000.27
Browser: Chrome Version 67.0.3396.99

If i create a process in arc and choose the All subset i get an error.  If i do the same in TI editor it works OK.

![subset error](https://user-images.githubusercontent.com/41028072/43305227-4671694e-91ba-11e8-905f-4278b9d42a0c.JPG)

**Comment by cubewise-tryan** [comment]
Hi @kmurphy111,

The REST API doesn't support the implicit "All" subsets unfortunately. They do exist under the covers when executing a TI but we can't return the values for the purpose of a preview. 

We are looking into some work arounds.

**Comment by cubewise-tryan** [comment]
Hi @kmurphy111,

This has been fixed. it will return all elements when the All subset is selected.
