### ISSUE TITLE
TI Error Log summary

### ISSUE THREAD

**Issue by uttergithub** [cubewise-code/arc-issues#174]
Nice to have: Instead of scrolling through reams of erroneous transactions, it would be nice to hit a button and view a summary of Dim:Element that didn't find a home.

**Comment by cubewise-tryan** [comment]
Hi @uttergithub,

Not sure what you are asking for. Can you give some more details?

**Comment by uttergithub** [comment]
Thought I'll leave it to your imagination.... ;-)

I find the error log tiresome in that you have to review it line by line to summarise the issues i.e. the same issue per errored transaction happens over and over again.

![2018-07-31 14_34_14-untitled - notepad](https://user-images.githubusercontent.com/37645851/43627791-20a9e0de-973b-11e8-84f8-6c443382f1fc.png)

And I don''t want to see all the junk in the transaction. Just a summary with;

"21433" not in Accounts
"21434" not in Accounts

something like that..

**Comment by cubewise-tryan** [comment]
Hi @uttergithub,

It is possible but not-planned at this stage. Each scenario would need to manually coded which is time consuming, it is a good idea but there are a number of core features we plan to add first.
