### ISSUE TITLE
Rule validation

### ISSUE THREAD

**Issue by jgorsk** [cubewise-code/arc-issues#175]
In TM1 advance rule editor there was one extremely useful functionality - checking the rule before saving. For bigger cubes that can save a lot of time if you make a typo (or mistake) that will result with feeder recalculation. Any chances to have that functionality in Arc?

K.

**Comment by cubewise-tryan** [comment]
Hi @jgorsk,

Yep, that is possible.

**Comment by cubewise-tryan** [comment]
Hi @jgorsk,

I looked further into it and the rule needs to be saved in the REST API before the syntax can be checked so unfortunately this isn't possible.
