### ISSUE TITLE
Add "create picklist cube" option to cubes

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#18]
Arc 0.9.2
In architect/perspectives there are some context menu shortcuts to make creating or editing control object extensions of a "base object" easier to access. Currently these options aren't available in Arc and creating such objects like picklist cube needs to be done in architect.

It shouldn't be necessary to add as a context menu or create a plugin. It would suffice to have one button to "create picklist cube" and then select the base cube that the picklist cube should be created for. (Or perhaps even make an intermediate dialog to the existing "create cube" dialog).

A cube viewer isn't required for this functionality since in 99.9% of cases a picklist cube will be populated exclusively by rule. It is important functionality to have since the developer can then stay workign in Arc without needing to go to architect to do such actions,

With regards to the idea of an intermediate dialog to the current create cube button this could function as follows:
- click "create cube"
- dialog with radio buttons or dropdown of type of cube to create (e.g. user cube, picklist cube, cell security, drill assignment, element security)
- depending on selection user gets appropriate dialog to create cube (picklist or drill assignment just select base cube name, element security select dimension, cell security select cube and then select relevant dimensions)
- after creation of cube focus taken by rule editor window of new cube

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

We will look at adding this in the future, in the interim these objects can be created manually as long as you follow the correct naming convention.
