### ISSUE TITLE
Add Global search abilities

### ISSUE THREAD

**Issue by brianknott** [cubewise-code/arc-issues#184]
Would be great if ARC could do a global search on all TI process or Rules.  For example if I have to remove all references to a cube in my processes, rules and feeder, because the cube has been removed, then ARC could return a list of the instances along with a link the instance.

**Comment by cubewise-tryan** [comment]
Hi @brianknott,

It is easier said than done in Arc, it would require us to pull to the browser every rule, process, etc which wouldn't be too efficient. We already have this feature in Pulse: 

![image](https://user-images.githubusercontent.com/22929868/44251360-6ec56300-a23b-11e8-87fb-4085fd626134.png)

There are plans to add integration with Pulse which would allow us to add this feature.
