### ISSUE TITLE
Unify find/replace between the TI code tabs

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#187]
Arc 1.0.0 PA 2.0.5 (TM1 11.3.00000.27)

It would be more user friendly if the find/replace feature in the TI editor could treat all 4 code tabs as a single document.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

The only easy way to add this feature is to combine all of the tabs (Prolog, Metadata, etc) into single editor as the find/replace functionality is built-in. Do you think that would work?

**Comment by lotsaram** [comment]
From my perspective it would be fine (even preferable) to have all the TI code tabs in a single editor. As long as there was some way of clicking on a shortcut to take the user to the start of each "tab" and it is obvious which code belongs to which tab then that is all that is needed.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

We have added and enhanced the built-in find to search across tabs.
