### ISSUE TITLE
Recent items description incomplete for hierarchies

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#188]
Arc 1.0.0

In the recent items shortcut for hierarchies just the instancename:hierarchyname is listed without the dimension name. The dimension name should be included, otherwise it isn't clear which dim the hierarchy is from.
![image](https://user-images.githubusercontent.com/29408388/44734147-8d541580-aae9-11e8-942f-b339f4ff3305.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

Another one that isn't so straight forward, we will look at this when we rewrite the menu system for #104.
