### ISSUE TITLE
Chores Duplicating Processes On Save

### ISSUE THREAD

**Issue by cubewise-plim** [cubewise-code/arc-issues#189]
Arc: 1.0.0

Below Chore was initially created as having only the '_ Long Pause' TI. But every time you save, the TI keeps on duplicating:

![image](https://user-images.githubusercontent.com/22946355/44789293-8dced800-abdf-11e8-9dd1-6b5d815b7954.png)

**Comment by cubewise-tryan** [comment]
Hi @cubewise-plim,

It seems the chore API has been changed, we will add a fix to handle the different versions.
