### ISSUE TITLE
Select Dimension Element

### ISSUE THREAD

**Issue by girishnam** [cubewise-code/arc-issues#190]
Hello,

In Arc how to select elements for the dimensions which are not matching for Cube to Cube rules, similar to advance rule editor in TM1.

Attached is the screenshot from Advance Rule Editor.

<img width="593" alt="screen shot 2018-08-30 at 4 45 47 pm" src="https://user-images.githubusercontent.com/42832679/44840910-b6ed7800-ac74-11e8-9fa7-2465bda6205a.png">

**Comment by cubewise-tryan** [comment]
#31
