### ISSUE TITLE
Debugger doesn't work for recursive ExecuteProcess calls

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#191]
Arc 1.0.0

If a TI process contains logic where it recursively calls itself with different parameters this isn't handled by the Arc debugger UI. Although you can see the ID of the line the code execution is paused on and the value of the watched variables the UI is otherwise stuck at the point the recursive sub-process was called in terms of highlighting of where the code execution is and mouse-over value of variables.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

The server implementation of the debugging doesn't seem to cater for a recursive process. The call stack always has one process but it should have one for every step in the recursion. 

I am going to close this one as I think it is an edge case and we can't change it.
