### ISSUE TITLE
Feature Request - Picklist or multi select in security manager

### ISSUE THREAD

**Issue by Dav0815** [cubewise-code/arc-issues#194]
Order to add a cube, dimension or any other object to a group I have to typ in the object name. It would be way better to show all relevant objects and tick them. A filter could then help to find a group of similar objects, but if I want to add 5 dimensions at the moment I have to start typing 5 times, select the object and start over again.

Arc version 1.1

**Comment by cubewise-tryan** [comment]
Hi @Dav0815,

You can type and then press Enter if the item is at the top. Type again, etc. Works quite well and is fast enough.
