### ISSUE TITLE
Highlighted word does not Auto-Populate in Find window

### ISSUE THREAD

**Issue by Sneb85** [cubewise-code/arc-issues#196]
I'm using arc v1.1.0 with PA 2.0.3 and Chrome v68

Previously in arc v1.0.0, highlighting text in editing area and then hit Ctrl+F to bring up the Find window will automatically fill in the Find window with the highlighted text. 

This behaviour doesn't exist in arc v1.1.0 anymore. Is it possible to bring it back? It was very handy.

**Comment by lotsaram** [comment]
For me this is also "essential feature"

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

If this is an "essential" feature you need to get out a little more! Having said that we will add it in the near future.
