### ISSUE TITLE
Deleting MDX view doesn't close tab

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#197]
Arc 1.1
TM1 11.3.000027
When deleting a MDX view with Arc the view is deleted but the tab in Arc isn't cleaned up and stays open as a "ghost tab". You can't do anything with the tab as all buttons are inactive. The tab can still be closed manually but this should happen automatically with the view destroy.

After deleting view tab looks like this.
![image](https://user-images.githubusercontent.com/29408388/45491902-27af8c80-b76b-11e8-90c4-6f0f58e08157.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

That is the intended behaviour, it is displaying a blank view. You can either select a view from the drop down or drag in the hierarchies to create a new view. You need to have a hierarchy on the rows AND columns before you can save the view.
