### ISSUE TITLE
Display waiting/executing when running process

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/arc-issues#198]
Hi,

When running a process in Arc it always says "executing".
![image](https://user-images.githubusercontent.com/42434036/45496746-71ea3b00-b776-11e8-9f24-0d4f91d25096.png)

It would be great (and allow developers to avoid going to Pulse/TM1Top/Sessions tab) if it said "waiting" in case it's blocked by another thread and then switch to "executing" when it's actually running.

**Comment by cubewise-tryan** [comment]
Hi @macmaj,

It would be a nice feature but the information required to implement this feature isn't provided by the REST API. All we know is that the HTTP request to the API hasn't returned.
