### ISSUE TITLE
Reorder TI buttons

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#2]
Would it be possible to reorder the TI buttons from
![image](https://user-images.githubusercontent.com/25290041/37639187-8035850e-2c64-11e8-9ee9-9dc468ed29f6.png)

The **Clone** button has the same behavior as a **Save As** button so it should be close to the **Save** button.

**Comment by lotsaram** [comment]
Even more padding between debug and delete would be nice.

**Comment by cubewise-tryan** [comment]
Hi @vviau and @lotsaram,

There are no plans to change the location or spacing of the buttons. There are lots of extra cool features we are working and that is the current focus.
