### ISSUE TITLE
Changing a ti parameter type results in an error on save

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/arc-issues#200]
Steps:
1) Create a string parameter
2) save the TI
3) change the string parameter to a numeric
4) save TI - error on saving

![error](https://user-images.githubusercontent.com/18215782/45522714-8da31080-b779-11e8-9533-689e90c00572.png)

The error is fixed if you put a number in the default value. A better behavior would be to warn the user to change the default value to a number if there was a default value; if there is not one, change it from a blank to a 0.

**Comment by cubewise-tryan** [comment]
Hi @rclapp,

It will now convert the default value from string to a number, if the conversion fails it will set the value to 0.
