### ISSUE TITLE
Show last modified information for TIs and Rules

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/arc-issues#203]
It would be really useful to show the last modified date/time/user for process and rules.

**Comment by cubewise-tryan** [comment]
Hi @rclapp,

Both would be nice to have but I don't believe the REST API has a last modified date for processes. For rules there is LastSchemaUpdate but that doesn't seem to be updated on a rule change. When we integrate Arc and Pulse we will be able to provide lots of more information like this.
