### ISSUE TITLE
Message Log shows 500 oldelst lines instead of showing 500 latest

### ISSUE THREAD

**Issue by 4rtem** [cubewise-code/arc-issues#211]
In order to get latest log entries I need to put 60 000 into ARC settings, otherwise I can see only 500 oldest lines related to Server Startup

**Comment by cubewise-tryan** [comment]
Hi @4rtem,

Please provide the Arc and TM1 versions when submitting issues. I can't replicate this issue.

**Comment by 4rtem** [comment]
Hi @cubewise-tryan 
-  ARC 1.1.1
-  TM1 11.2.00000.27

**Comment by cubewise-tryan** [comment]
Hi @4rtem,

TM1 11.2 has a bug that stops delta queries working in the REST API which is what the server log uses. You will need to upgrade to 11.3.

**Comment by 4rtem** [comment]
Thanks!

**Comment by matto4** [comment]
Hello, I am facing similar issue. After opening Server logs it shows at first oldest messages and from tm1server.log.6. But after about 30s it switches automatically to the newest. This is happening every time I close and open Server logs. 

Arc version 1.2.1
TM1 version 11.4.00000.21-0

Thank you.
