### ISSUE TITLE
Security: Name and Display name are the same

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#217]
Arc version 1.1.2
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

When using CAM authentication the Name and Display name are both showing the same value. Instead the Display Name should be the }TM1_DefaultDisplayValue

![image](https://user-images.githubusercontent.com/39726565/46011977-f10d3680-c0c7-11e8-83b6-4a2334874d66.png)

![image](https://user-images.githubusercontent.com/39726565/46012007-05513380-c0c8-11e8-9ddc-20b918faa86d.png)

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor,

Arc is displaying the FriendlyName from the REST API, there is an enhancement request with IBM to change this with the display name.
