### ISSUE TITLE
Freeze row header when horizontal scroll to right

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#219]
Arc 1.1.2
TM1 11.3.00003

This aplies to both the hierarchy editor and cube viewer.
The column headrs are to use web development terminology "sticky" or to use the more familiar spreadsheet frame of reference are "frozen" so when rows are scrolled down you can still see  what the data in each column relates to. However _**the same isn't implemented for rows**_. If you have a dimension with a lot of attributes or a cube view with more then about 15 columns (depending on monitor resolution) then when you scroll to the right the row header is lost.

It is pretty essential not to lost the frame of reference of the cvells you are looking at. Both column and row headers need to be sticky.

**Comment by cubewise-tryan** [comment]
This has been added to the dimension editor. It isn't so easy to add to the cube viewer and therefore we don't have plans to add it at the moment.

**Comment by lotsaram** [comment]
@cubewise-tryan it may be difficult to add to the cube viewer but it is an essential feature. It isn't a cube viewer unless both row and column headers are frozen. As a user you need to know the context of the cells.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

No, it isn't essential, it is a nice to have. Not having a cube viewer at all or a rule editor is essential. We may look at adding it the future but it isn't a high priority.
