### ISSUE TITLE
Cube list view enhancement

### ISSUE THREAD

**Issue by lbrowncubewise** [cubewise-code/arc-issues#22]
A nice enhancement to the Cube list view would be to have the Logging flag next to the dimensions, saves us having to go into the Cube control cube to find it.

![image](https://user-images.githubusercontent.com/35220689/37863998-06e31b54-2f60-11e8-8572-21b01965d919.png)

**Comment by lbrowncubewise** [comment]
@gpool21 I can't see this in the 1.1.3 release?

**Comment by gpool21** [comment]
@lbrowncubewise My mistake - should have been 1.1.4
