### ISSUE TITLE
Process validation

### ISSUE THREAD

**Issue by cwcibo** [cubewise-code/arc-issues#220]
It is somehow related to https://github.com/cubewise-code/arc-issues/issues/175 so I expect the same answer, however, it would be very useful to have a process validation when saving it. If something is wrong from the variable declarations point of view there is no notification at saving and if it is then executed, we end up with a generic error and no details anywhere in the log.

**Comment by cubewise-tryan** [comment]
Hi @cwcibo, 

The process is validated for errors when saving, can you provide an example of a variable issue that you talk about?

**Comment by cwcibo** [comment]
Hi. I will try to replicate the case and provide additional inputs.

**Comment by cubewise-tryan** [comment]
Hi @cwcibo,

Just checking what version of TM1 you are using? Process validation was added in TM1 11.

**Comment by cubewise-tryan** [comment]
Hi @cwcibo,

Any update? Can you confirm the version of TM1 you are using?

**Comment by cwcibo** [comment]
The version is 10.2.2 FP7.
