### ISSUE TITLE
Display Name incorrect in Security tab

### ISSUE THREAD

**Issue by psegal** [cubewise-code/arc-issues#224]
Arc 1.1.2
PA 2.0.4
Firefox, Vivaldi
Security is 2.

After a search for users in the Security Tab the Display Name in the result does not refresh correctly. 

![displaynameerror1](https://user-images.githubusercontent.com/27949728/46142850-2a70ae00-c250-11e8-89b5-fbe9731becda.png)
![displaynameerror2](https://user-images.githubusercontent.com/27949728/46142886-47a57c80-c250-11e8-8d95-9977b877520c.png)

**Comment by psegal** [comment]
So, this is closed but not fixed until 1.1.4? I would have thought better to close when the bug is fixed rather than when it's put on a list.

**Comment by psegal** [comment]
Meant to say, the audit and settings icons action the Display Name rather than the Name, so they become effectively useless. I haven't dare try the delete icon ;-)

**Comment by lotsaram** [comment]
@psegal I would imagine it is fixed in the 1.1.4 code branch. Just that this isn't release yet.

**Comment by cubewise-tryan** [comment]
Hi @psegal,

It has been fixed in 1.1.4 which will be the next version we release.
