### ISSUE TITLE
Changes are not committed when running process from ARC with Minor Errors

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/arc-issues#227]
When running following testing process with parameters pFailTheProcess=0 and pMinorError=1, the dimension is not created and everything looks like the process has rolled back the results (PAL 2.0.5 - rollback should occur only in case of major error or ProcessError, ProcessRollback, ProcessQuit).
When on the other hand running the same process with the same parameters from Architect, dimension is created properly.
Parameters:
![image](https://user-images.githubusercontent.com/43746968/46285233-0fb57680-c57b-11e8-8025-f4e28cd36244.png)

Data Source:
![image](https://user-images.githubusercontent.com/43746968/46285271-35db1680-c57b-11e8-9e05-17d7330341b4.png)

Prolog:
![image](https://user-images.githubusercontent.com/43746968/46285294-44293280-c57b-11e8-8270-9bc5a0ff7efd.png)

Metadata:
![image](https://user-images.githubusercontent.com/43746968/46285313-530fe500-c57b-11e8-9b5b-312c8f3c94e1.png)

Data and Epilog: Empty

**Comment by rclapp** [comment]
This is a known bug in the REST api. The execute function does not properly handle errors as you mention above. This has been acknowledged as a defect. According to IBM it is fixed in 2.05 with the introduction of the ExecuteWithReturn function. Arc would obviously need to adopt these functions to fix it as well.

**Comment by cubewise-tryan** [comment]
Hi @pbuncik & @rclapp,

Yes, this is a know bug in TM1. There is also a bug in 2.0.5 that causes ExecuteWithReturn to crash the server, Arc already supports ExecuteWithReturn but only on 2.0.6 (which isn't out yet). A new version of Arc will be out later today that uses ExecuteWithReturn on 2.0.5 IF1 or later. On prior versions Arc will uses the Execute action that rolls back changes when there is a minor error.

**Comment by cubewise-tryan** [comment]
Hi @pbuncik,

To retrieve the error log when using ExecuteWithReturn you need to expand the ErrorLogFile like so: `/tm1.ExecuteWithReturn?$expand=ErrorLogFile`

It will crash the server if there isn't an error.
