### ISSUE TITLE
NVALUE SVALUE VALUE_IS_STRING missing after save in Arc

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/arc-issues#228]
I performed a file comparison after saving a process in Arc without changing anything and noticed that after the save the local variables NVALUE, SVALUE, VALUE_IS_STRING are no longer in the the process.

I also see that some other process internals changed after the save and it looks to me, but not 100% sure, that these are also related to these missing local variables.

The process I tested has 13 variables and including these 3 local variables that sums up to 16. 

In the original file I see several internals like 577,16 (under this one NVALUE, SVALUE, VALUE_IS_STRING are located) 578,16 579,16 580,16 581,16
After the save the aforementioned numbers refer to 13 instead of previously 16.

**Comment by lotsaram** [comment]
Are you sure you didn't change the data source type from view to something else? Because the implicit local variables nValue, sValue and value_is_string are only generated for processes where the datasource type is 'VIEW'.

**Comment by hermie64** [comment]
I did not change the data source. I opened the process, saved it in Arc and performed a file diff.
If it's helpful I could send you the original process plus after-save-version for analysis.

**Comment by lotsaram** [comment]
I observe the same thing when doing a diff of the .pro file edited Arc vs. Perspectives/Architect. I don't observe any difference in behavior of the process while running the process and Arc still allows me to use the nvalue, svalue and value_is_string variables without having declared or set them.
I haven't tested saving the process with Workspace to see if the variables are generated in the .pro file however my assumption based of this test is that the variables are an artifact of the editor in Architect/Perspectives and are not actually required.

**Comment by cubewise-tryan** [comment]
Hi @hermie64,

As far as I am aware those system variables are implicit and are created whenever a view is used as a data source. They exist whether they are in the variables tab or not. Is it causing a problem?

**Comment by hermie64** [comment]
Hi @cubewise-tryan,

I didn't notice a different behavior because of these missing implicit local variables and @lotsaram confirmed that.
It's just that I was expecting the same content of .pro file regardless of using native TI editor or Arc.

**Comment by cubewise-tryan** [comment]
Hi @hermie64,

Thanks for the feedback. We have made the best efforts to make sure developing with Arc is compatible with Architect. There are a few quirks to make them work along side each other, given this one doesn't have an impact I will close the issue. If we find it has an impact we can reopen.
