### ISSUE TITLE
Setting a chore to active/inactive in Arc is not being reflected in Architect

### ISSUE THREAD

**Issue by lbrowncubewise** [cubewise-code/arc-issues#23]
When setting a chore to active or inactive in Arc, at my client site, it is not being reflected in Architect or being saved to TM1, I had set a chore to Active in Arc but this was not reflected in TM1 and the chore did not run.

**Comment by lbrowncubewise** [comment]
This only seems to happen on the Chore screen, the Chore overview screen does activate chores.

![image](https://user-images.githubusercontent.com/35220689/37879777-d94065a0-3075-11e8-8e92-61c24dc98250.png)

**Comment by cubewise-tryan** [comment]
Hi @lbrowncubewise,

This is a bug in the REST API, it doesn't allow you to update the Active property directly. It has been reported to IBM, when it gets fixed there it will be fixed in Arc.
