### ISSUE TITLE
Cube Viewer: freeze row header

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#233]
@vviau in the release notes for 1.1.3 #219 is listed as fixed in the cube viewer. However it isn't fixed in the cube viewer, only in the hierarchy editor.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

We don't have plans to fix the column headers at this stage.

**Comment by lotsaram** [comment]
I get that you don't plan on fixing it (don't agree with it but I get it).
My point was that in the [release notes](https://github.com/cubewise-code/arc-issues/blob/master/releases/v1.1.3.md) you say it's fixed but it isn't. The release notes should be corrected.

**Comment by vviau** [comment]
The release notes have been updated.

Thanks @lotsaram
