### ISSUE TITLE
Security: cannot add user to group

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#235]
Arc version 1.1.3
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

In a model which uses CAM you cannot add a user to the group. I tried to add my colleague Mateusz to ADMIN group and I got the following error: "cam.id/user name can not be found in collection of type 'User'.

Please note that this user will be displayed as a CAM id in the table, but in the message Arc will actually display the proper user name. Maybe this could help on #217 

![image](https://user-images.githubusercontent.com/39726565/46406335-7b2e4e00-c70b-11e8-9732-6582c64b79b4.png)

**Comment by gpool21** [comment]
Hi @RaduCantor 
Currently the FriendlyName (Mateusz in your example...) is not accessible via the REST API directly.
For the next ARC release one will be able to add the user in a CAM security setup by referencing the full CAMID though.
Not ideal, but we are looking into options to simplify this.

To add a single user to the group one can either:
- From the 'Groups' tab, type the user name in the 'Add User' column against the ADMIN group
(so in CAM it should be the full CAMID ) or
- From the 'Users' tab, in the 'Add to Group' column, type the group name (eg, Admin) against the user name (so the CAMID line)

**Comment by gpool21** [comment]
Hi @RaduCantor 
Currently the FriendlyName (Mateusz in the screenshot...) is not accessible via the REST API in a CAM security setup.
From the next ARC release one will be able to add a user in a CAM security setup by referencing the full CAMID though.
Not ideal, but we are looking into options to simplify this so one can leverage the friendly name.

For adding a single user to a group there are two options:
- from the 'Users' tab, against the identified user line, type the group you want to add the user to in the 'Add to Group' column
(so in the screenshot above, one should type 'Admin' against the user line not 'Mateusz')

- from the 'Groups' tab, against the group line you want to add the user to, type the user name
(so in the screenshot above, it will be the full CAMID)
