### ISSUE TITLE
ARC is not recognising the process completion

### ISSUE THREAD

**Issue by dwigsy** [cubewise-code/arc-issues#236]
![image](https://user-images.githubusercontent.com/39814816/46446332-0f0d2200-c7bf-11e8-89f4-2dc6cf9bf2bd.png)

When process completes, the notification is not received. To change the process afterwards, have to execute and use the save before execution dialog to save changes, as the save icon is no longer available (process running so disabled).

Will restart PC and see if that resolves the issue, nothing in the ARC log.

**Comment by cubewise-tryan** [comment]
Hi @dwigsy,

What is the version of Arc and TM1? Can you also check the Console in the Developer Tools (F12), there is likely to be an error.

**Comment by dwigsy** [comment]
I’m using the very latest… 1.1.3

[cid:image002.png@01D45BF4.5F325930]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

Note that it has actually executed the process on the server, so something is happening…

________________________________
