### ISSUE TITLE
TI ascii source files with TAB delimiter

### ISSUE THREAD

**Issue by nooce** [cubewise-code/arc-issues#238]
Greetings,

Each time I try to run a process with ASCII datasource and using a {TAB} delimiter I get the message
{"error":{"code":"91","message":"SystemParameterTypeInvalid"}}
on Preview

Regards

**Comment by nooce** [comment]
Hi,

PA 2.0.5 and TM1 10.2.2 fp6
ARC 1.0, 1.1, 1.1.1, 1.1.2, 1.1.3
actually it has never worked.

regards



Le 8 oct. 2018 à 00:26, tryan <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @nooce<https://github.com/nooce>,

Can you please provide the version of Arc and TM1?

**Comment by cubewise-tryan** [comment]
Thanks, we will look into it.

**Comment by nooce** [comment]
Hi,

Can't use tab as ASCII delimiter.
it seems the problem is back with the 1.3.1 version

Regards
