### ISSUE TITLE
Valid view definition not found error message

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#239]
Arc 1.1.3
TM1 11.3.00003.1

For MDX views created by the TI function ViewCreateByMDX when they are opened in Arc the error message is displayed "A valid view definition was not found, MDX will need to be edited manually."
The views retrieve data correctly on refresh, but the row/column/filter context of the dimensions is not shown in the view builder GUI. SO effectively the only way to edit the view is by manually editing the MDX statement.
![image](https://user-images.githubusercontent.com/29408388/46600868-d4bbc180-caeb-11e8-8c54-e85d5a1886a4.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

We don't have a parser in Arc to convert an MDX statement into a row/columns definition. If you create a MDX view outside of Arc (or Canvas) you will need to edit the MDX directly. We may look at it in the future but it isn't easy, MDX is a very expressive / flexible language so it would be difficult to support it except for the most simple cases.
