### ISSUE TITLE
Error message does not open when clicking on the top right corner icon

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#24]
Hi,

Arc: 0.9.2
TM1: 11.0.00204

When a process fails, it would be great if the error icon in the top right corner would show the same pop up as the one in the left bar menu:

![image](https://user-images.githubusercontent.com/25290041/37887382-2d0a8f5c-310d-11e8-9b49-33e73be4c813.png)

When I click the one in the menu I get the popup:
![image](https://user-images.githubusercontent.com/25290041/37887460-9991d93c-310d-11e8-9710-814227b82425.png)

But when I hover the error message on the top right corner, it looks like we can click on it but nothing is happening:
![image](https://user-images.githubusercontent.com/25290041/37887437-74379c94-310d-11e8-92f3-86f67f39e846.png)

Cheers,

Vincent

**Comment by cubewise-tryan** [comment]
Th @vviau,

The icon shows the number of error message rather than the last one and clicking the button shows the menu if it is closed. Given the icon will show multiple errors I think it might be confusing to show the last one.
