### ISSUE TITLE
Hierarchy editor doesn't work for large dimensions

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#241]
Arc 1.1.3
TM1 11.3.00003.1

When Arc loads the dimension/hierarchy editor it attempts to load for _**all members**_ (all elements with all consolidations expanded). I have a date dimension with 60K elements but due to some alternate rollups the main hierarchy has over 1M members. As Arc is trying to render over 1M rows in the browser eventually it runs out of memory and crashes the browser tab.

Arc should check the dimension size and for hieraarchies over a certain size should only return the first 1000 members. It is far more preferable to need to pagenate than have a hanging browser that eventually crashes.
![image](https://user-images.githubusercontent.com/29408388/46870533-2a1b0a00-ce2f-11e8-8908-5e238683f0b3.png)
... and eventually
![image](https://user-images.githubusercontent.com/29408388/46870554-369f6280-ce2f-11e8-9a30-a2eac2562170.png)

As a comparison the same dimension in Architect dimension editor while not exactly instant still loads in under 5 seconds.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

It works well enough large-ish dimensions, approx 20k elements. We can put a cap and warning so you don't get an error but it will be limited to that size. In terms of supporting very large dimensions I think it isn't really needed a they should be maintained via TI.

**Comment by cubewise-tryan** [comment]
By default it will now limit the number of elements to 10,000. You can change the value in the About page settings.

**Comment by lotsaram** [comment]
I think it's a good move to put a check on the number of elements. But it isn't really the number of elements but the number of members. It should be the number of members that gets checked not the number of elements (or else return TM1SubsetAll and not Dimension.Members as the default for the hierarchy editor).
Another solution other than not opening large dimensions would be to offer a prompt to open with root elements only and let the user then expand only the nodes they want to edit.
e.g. if dimension size over threshold then display the following set
{Filter( { TM1SubsetAll([DIMENSION] )}, [DIMENSION].CurrentMember.Parent.Name = "" )}

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

Thanks for the clarification, we have made it check the members count. Allowing the expanding elements would mean re-writing a lot of the current editor so we will leave it as is for the time being.

It looks like this:
![image](https://user-images.githubusercontent.com/22929868/46942766-bb051600-d0b9-11e8-8280-5c4fb1925b9b.png)
