### ISSUE TITLE
Enhance execute process modal dialog to include parameter names

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#242]
Arc 1.1.3

It would be an improvement if the Arc process execute modal actually included the parameter names (and maybe a numeric/string indicator as well?) not just the prompt string. As Arc is a IDE this is relevant for developers. It makes things easier for us if we can see the parameter names!

e.g.
![image](https://user-images.githubusercontent.com/29408388/46871091-b7ab2980-ce30-11e8-82cc-f8345999eaba.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

It currently shows the parameter names if the prompt doesn't exist. What we can do is add a placeholder in the input box itself so you can see the name and type.

**Comment by cubewise-tryan** [comment]
The placeholder wasn't the best place as numeric parameters always have a default value. Instead they have been added to the title:

![image](https://user-images.githubusercontent.com/22929868/46924282-ed3d5600-d06e-11e8-9c9d-85955bbef190.png)
