### ISSUE TITLE
Filtered consolidation won't expand

### ISSUE THREAD

**Issue by psegal** [cubewise-code/arc-issues#243]
PA 2.0.5
Arc 1.1.3
Firefox 

Filtering for a consolidated element in a dimension: once found the consolidated element won't expand to view the n elements beneath it. 

This may be expected behaviour or I may well be missing something, but for a long-ish dimension this is something I use all the time to e.g. amend aliases on n elements below the c element.
![dimfilter1](https://user-images.githubusercontent.com/27949728/46943485-a5ff9700-d067-11e8-9f37-0f55359aed88.png)
![dimfilter2](https://user-images.githubusercontent.com/27949728/46943486-a5ff9700-d067-11e8-8ddd-0fc34b70fec5.png)

**Comment by cubewise-tryan** [comment]
Hi @psegal,

The filter is filtering the name/alias so it will only display an item when it contains the text. Toggling the expand/collapse has no effect unless the filter text is in the name of the child also. 

We might be add some functionality similar to the subset editor that gives you a bit more flexibility. We will look in to it.
