### ISSUE TITLE
TI Editor: Variable name with space

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#245]
Hi,

Arc v1.1.4.

When the dimension source contains a space such as "T Date", Arc will create a variable called "vT Date" as you can see below:

![image](https://user-images.githubusercontent.com/25290041/47004539-6074c400-d164-11e8-9b9f-96d2344417aa.png)

It would be great if the TI Editor just remove the space in the name and create a variable "vTDate" instead.

Cheers,

Vincent

**Comment by cubewise-tryan** [comment]
Hi @vviau,

That is something we should be able to fix easily enough. It should still work as is? Just remove the space when using the variable in your TI code.

**Comment by cubewise-tryan** [comment]
Fixed, it will remove any other invalid characters.
