### ISSUE TITLE
How to make a new process to appear in auto-complete?

### ISSUE THREAD

**Issue by Cubewise-Ce** [cubewise-code/arc-issues#246]
Hi,

Everything is in the title: I just created a new process I want to call with ProcessExecute() function from another process, but this new process doesn't appear in the proposed list when using the intellisence. How is the auto-complete updated? Is it a matter of time or refresh the page or restart Arc?

Arc Version: 1.1.3
TM1_version=TM1-AW64-ML-RTM-11.0.4.96-0

Cheers

**Comment by cubewise-tryan** [comment]
Hi @Cubewise-Ce,

Refreshing the browser will do the trick.
