### ISSUE TITLE
Highlight when an object is unsaved

### ISSUE THREAD

**Issue by Cubewise-Ce** [cubewise-code/arc-issues#247]
Hi!

That could be great to have a little dot by the name, or a different name color, or something to tell the object is not modified but not saved. What do you think? 

Cheers

**Comment by cubewise-tryan** [comment]
Hi @Cubewise-Ce,

That is a good idea, if it is easy to implement we will add it.

**Comment by cubewise-tryan** [comment]
Hi @Cubewise-Ce,

After investigation it is much harder than first thought so we won't implement it at this stage. Nice idea though.
