### ISSUE TITLE
Cube is not populated if ItemReject occurs in process

### ISSUE THREAD

**Issue by Cubewise-Ce** [cubewise-code/arc-issues#248]
Hi, 

I've got a "process 1", doing some errors management, populating "cube 1" and calling other processes.
The error management does: 
- In data tab: some checks on each record, if an error is found: asciioutput in a file, nbError = nbError + 1, Itemskip. 
- In the epilog: if nbError <> 0, then ItemReject ('Please look at log file to check errors')

When the process is run from Arc:
- if no errors are trapped, the cube is populated correctly
- if some errors are trapped, and the ItemReject statement occurs, "cube 1" is not populated with the records not skipped.

When the process is run from Architect, everything works as expected: the correct records are populated.

In both cases, the message log shows the exact same thing : process finished successfully with the warning, same process calls in the same order with the same amount of execution time.

"Process 1" calls process 2 and process 3. 
Process 2 and 3 do not have any error management, and they populate cube 2 and cube 3. 
When run separately from ARC, cube 2 and cube 3 are populated correctly. 
When run from process 1, which has the ItemReject and doesn't populate cube1, cube 2 and 3 are not populated either.

I could replicate the behavior of "no data populated if ItemReject occurs" by adding an item reject statement at the end of simple copy process. 

Is this a parameter to switch off somewhere or a version issue ? Would you be able to help with this?

Arc Version: 1.1.3
Chrome: Version 69.0.3497.100 (Build officiel) (64 bits)
TM1_version=TM1-AW64-ML-RTM-11.0.4.96-0

Cheers

**Comment by lotsaram** [comment]
Hi @Cubewise-Ce  see #227 
This is a known issue to do with the Rest API

**Comment by Cubewise-Ce** [comment]
That was quick!

Thanks @lotsaram

**Comment by cubewise-tryan** [comment]
Hi @Cubewise-Ce,

As @lotsaram says, your will need to be on TM1 11.3 (2.0.5) IP1 and Arc 1.1.3 or later.
