### ISSUE TITLE
TI Cannot save changes with an ODBO datasource

### ISSUE THREAD

**Issue by lbrowncubewise** [cubewise-code/arc-issues#254]
When using TI editor with an existing process that has an ODBO datasource an error is presented, but the Save With Errors button does not save any of the code changes.

![image](https://user-images.githubusercontent.com/35220689/47254367-6ff05780-d459-11e8-85f1-177a2dd117d4.png)

**Comment by cubewise-tryan** [comment]
Hi @lbrowncubewise,

ODBO doesn't seem to be supported in the REST API so there isn't a lot we can do about it until it is added there This is a duplicate: #183

**Comment by lbrowncubewise** [comment]
@cubewise-tryan is there no way to allow us to update the Prolog through Epilog tabs and leave the datasource ODBO side alone as not supported by the REST API?
This would serve as a half-way house until such time as ODBO is support in the REST API
