### ISSUE TITLE
Unable to download Arc for TM1

### ISSUE THREAD

**Issue by PhilWorner** [cubewise-code/arc-issues#257]
**Describe the bug**
When clicking on the download link from https://code.cubewise.com/arc-download/ a popup box appears to save the file. After saving the file the download then fails and is not completed.

**To Reproduce**
1. Go to 'https://code.cubewise.com/arc-download/'
2. Click on 'Arc Download 1.1.3'
3. Click Save
4. See error - file will not download

**Expected behavior**
The file would download like any other

**Screenshots**
![image](https://user-images.githubusercontent.com/44384573/47328196-a1248e00-d6cc-11e8-8ee4-a1e8a1ff677e.png)

**Desktop (please complete the following information):**
 - TM1 Version: PA 2.0.2
 - Browser Chrome and IE
 - Arc Version 1.1.3

**Additional context**
Trying to download in New Zealand

**Comment by cubewise-tryan** [comment]
Hi @PhilWorner,

Are you on a corporate network? I have just tried and it worked for me. It is possible that it may be blocked by a proxy.

**Comment by PhilWorner** [comment]
Yes, that could possibly be it. I can try this evening at home and try it that way.
Thanks
Phil

**Comment by cubewise-tryan** [comment]
Hi @PhilWorner,

Can you try now? We have moved the download location.

**Comment by PhilWorner** [comment]
Hi
Yes it has worked now. Thanks!
