### ISSUE TITLE
Bulk Remove History

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/arc-issues#258]
**Is your feature request related to a problem? Please describe.**
At the moment when I opened an object using Arc, I can see history is saved and displayed on the top left hand corner, but unfortunately I will need to remove them one by one and this is quite annoying, would be nice that I can have a place to remove them all at once.

**Describe the solution you'd like**
A button or shortcut key to remove all history.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lotsaram** [comment]
I can't find the ticket number but I requested this once before as well.

**Comment by tatwong** [comment]
I searched and I couldn't find one neither.

**Comment by cubewise-tryan** [comment]
Hi @tatwong & @lotsaram,

You can remove them all by going to the About page and setting **Page History Maximum** to zero. Next time you open a page everything will be removed.

We are going to refactor that section and add a favourites option so it will change in the near future.

![image](https://user-images.githubusercontent.com/22929868/47389979-ee9f0a80-d761-11e8-978d-f741b5b702c3.png)
