### ISSUE TITLE
Log Off a TM1 Instance

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/arc-issues#259]
**Is your feature request related to a problem? Please describe.**
There are occasion when I wanted to disconnect / logoff from a server, especially when we want to do searching, on our environment, we have over 8 TM1 instances shown on the list, and when we want to search some objects and it return many of them.

**Describe the solution you'd like**
A place to logoff a particular TM1 instance, at the moment, only way to log off is close the browser, but this is not what I want.

**Describe alternatives you've considered**
No other alternative.

**Additional context**
N/A

**Comment by lotsaram** [comment]
Yes I agree if you work with multiple instances it would be much better to be able to log off. The only alternative now is to completely close the browser.

**Comment by vviau** [comment]
Hi @tatwong ,

To filter the search to show results only for one instance, you can use **i:instancename**, more information here:
https://code.cubewise.com/arc-docs/filtering-the-search-by-instance-and-objects

You can also filter by type using **t:process** or just **t:p** to show only processes.

**Comment by cubewise-tryan** [comment]
#38
