### ISSUE TITLE
Population of Attribute Function Overwrites Preceding Syntax

### ISSUE THREAD

**Issue by RRicafranca** [cubewise-code/arc-issues#26]
Hi,

When highlighting a "!" element and choosing an attribute using Ctrl + Space, the preceding syntax gets overwritten.

Example:

 Step 1:
 
![image](https://user-images.githubusercontent.com/37824482/37947573-e0372ddc-3159-11e8-90d2-c2021cbe30f6.png)

 Step 2: 

 
![image](https://user-images.githubusercontent.com/37824482/37947584-f43159d4-3159-11e8-9e6b-1aa2de7abe47.png)

(Notice that the preceding syntax "!Year" gets cut off.  In other tests, the character length that gets cut off varies.)

Version of Arc: 0.9.2
Version of TM1: 11.1.00004.3

**Comment by cubewise-tryan** [comment]
Fixed in 0.9.3
