### ISSUE TITLE
Create Process before Saving

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/arc-issues#260]
**Is your feature request related to a problem? Please describe.**
When creating process in Arc, we always need to create it first with a proper naming, but alot of times I may prefer to write up a process first and then decide how I should name the process, this is how current Perspective/Architect behaving at the moment.

**Describe the solution you'd like**
When click the "+" sign, I get a page as <<Unnamed TI #>> as an example.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cubewise-tryan** [comment]
Hi @tatwong,

The way Arc has been designed in isn't possible to do this unfortunately, it is a good idea and probably preferable. The object needs to be be created for the editor to work.
