### ISSUE TITLE
Auto Complete Key Binding not working

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/arc-issues#261]
**Describe the bug**
Tried to define the Auto Complete Key Binding, seems not taking any effect after I clicked "Save".

**To Reproduce**
1. Go to About
2. Update the value from Ctrl-Space to Shift-Space.
3. Click Save
4. Test on the TI editor, not work.

**Expected behavior**
After updated the Auto Complete Key, I should get the behaviour immediately.

**Screenshots**
![image](https://user-images.githubusercontent.com/43463864/47342403-37a97d00-d6d6-11e8-87d3-3164a90eeba8.png)

**Desktop (please complete the following information):**
 - TM1 Version: 10.2.2 FP7
 - Browser: IE 11.0.9600.19100
 - Arc Version : 1.2

**Additional context**
Reason I need to change this is because we are using Chinese Windows, Ctrl-Space is to change the language setting.

**Comment by cubewise-tryan** [comment]
Hi @tatwong,

This works for me, steps:
1. Change **Auto Complete Key Binding** in about page to Shift-Space
1. Refresh browser
1. Press shift+space to show auto complete

Check to see if the refresh fixes the issue.

**Comment by cubewise-tryan** [comment]
Hi @tatwong,

Any update?

**Comment by tatwong** [comment]
Hi @cubewise-tryan , it is working now, thanks!
