### ISSUE TITLE
Cube Viewer - Input cells display issue

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/arc-issues#265]
**Describe the bug**
Selecting and then deselecting input cell breaks displayed value.
This has happened for me when a cell:
- Displays % value
- Displays value with thousand separators
This doesn't happen when value has only decimal separator.
Additionally, columns and column headers become misaligned.

Issue disappears on view refresh.

**To Reproduce**
1. Open view with input cells
2. Select an input cell (e.g. with double-click)
3. Click outside the cell e.g. select different cell

**Expected behavior**
Displayed value doesn't break

**Screenshots**
![image](https://user-images.githubusercontent.com/42434036/47354059-00c76d00-d6be-11e8-98bd-91bd7fc2c068.png)
![image](https://user-images.githubusercontent.com/42434036/47354041-fad18c00-d6bd-11e8-9ce4-24b0e49bcd89.png)

**Desktop (please complete the following information):**
 - TM1 Version - 2.0.4 
 - Browser - Chrome
 - Arc Version - 1.2.0

**Comment by lotsaram** [comment]
This sounds a lot like #231 (value of input cell truncated to first comma on enter or tab key)

**Comment by cubewise-tryan** [comment]
Hi @macmaj,

See notes here: #232
