### ISSUE TITLE
Disable Multi-Tab

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/arc-issues#266]
**Is your feature request related to a problem? Please describe.**
The new multi-tab/multi-window feature from 1.2 is "great" if I am on a fast network, but it is now a pain when I am working from a slow network, when I click on a tab, say a TI process, my focus is still on the previous tab, say it's a dimension editor, by the time the TI process "response", it thinks I am trying to move the tab and then causing everything to hang on my browser, the only way to fix it is to click the "x" button on the top left hand corner, like after 10~20 seconds, or alternatively, just close my entire browser.

**Describe the solution you'd like**
A place to disable the multi-tab/multi-window feature, or hopefully can improve the selection sensitivity over a slower network.

**Describe alternatives you've considered**

**Additional context**

**Comment by cubewise-tryan** [comment]
Hi @tatwong,

You didn't provide the browser you are using but I assume it is IE. I would recommend using another browser: Chrome, FireFox or Edge. IE has a very slow JavaScript engine compared to the others which causes lag and other problems.

**Comment by tatwong** [comment]
The version of browser is IE 11.0.9600.19100

Unfortunately it is super difficult to get Chrome or any modern browser installed, but I get what you are saying.

**Comment by cubewise-tryan** [comment]
Hi @tatwong,

We will have a look and see if there is anything we can do as there is no way to disable (other than removing) the multi-tab feature. There are a number of "portable" versions of browsers that just need files to be copied to a computer which is the way I would go.

**Comment by cubewise-tryan** [comment]
Hi @tatwong,

We have found a way to disable the dragging. Use this new setting:

![image](https://user-images.githubusercontent.com/22929868/47541838-877e8300-d926-11e8-96b3-3712fee0d572.png)
