### ISSUE TITLE
Chore Editor deletes DST setting

### ISSUE THREAD

**Issue by OlafFranke** [cubewise-code/arc-issues#268]
**Bug Describtion**

If you set DST option in a Chore with Architect and re-open it in arc the time shows +1 hour; saving the Chore it looses the DST setting. Basically I we want to keep the DST setting.
(Key: 537,1 changes to 537,0).

**To Reproduce**
1. Have a Windows Server for TM1 with "Deutschland" regions settings (includes DST setting)
2. Open the Architect and create a Chore, add some dummy Process.
3. Set in "Schedule the Chore" the start time e.g. 14:00 h; important: set option "Run Chore time in ..." to "Local Server Time (will run at this local server time in DST or ST)"
4. Set e.g.: "Run Chore e very 1 day". (not important which time range)
![image](https://user-images.githubusercontent.com/44433920/47429180-cfba6b80-d795-11e8-982a-d6c2667f1ee6.png)
5. Save the Chore with some name
6. Open Chore in arc: it shows "03:00:00 PM" (what is not corerct).
![image](https://user-images.githubusercontent.com/44433920/47429101-97b32880-d795-11e8-8b35-137fdbe5f3dc.png)
7. Do nothing, save the Chore only.
8. Open the Chore again using the  Architect: the time is now 15:00 h, the option "Run Chore time in ..." changed to: "UTC Time (will run at this UTC time in DST or ST)"
![image](https://user-images.githubusercontent.com/44433920/47429306-48212c80-d796-11e8-9e8d-0d36d3f1e26f.png)

**Expected behavior**
The DST-setting must stay the same because the benefit of this setting is that the support don't have to change all UTC times of Chores if the time in Europe switches  from sommer to winter time.

**Desktop**
 - TM1 Version: 11.3.3.1
 - Browser Chrome 65.0
 - Arc Version 1.1.3

**Additional context**
The behavior I saw also in pre 1.0 arc versions.

**Comment by cubewise-tryan** [comment]
Hi @OlafFranke,

This is a bug in the REST API (at least up to 11.3/2.0.5), the "DSTSensitive" property is ignore when updating a chore and is always set to false.

**Comment by cubewise-tryan** [comment]
It is the same issues in 11.4/2.0.6. We will get in contact with IBM re a fix.

**Comment by OlafFranke** [comment]
Hi,

has anyone already reported this bug to IBM? Any idea?

Viele Grüße

Olaf Franke
selbstständige externe Fachkraft

im Auftrag der: NTT Data Deutschland GmbH
Hans-Döllgast-Straße 26 | D-80807 München

im Auftrag der: DB Netz AG

Projekterreichbarkeit:
Theodor-Heuss-Allee 5-7, 60486 Frankfurt a. Main
Tel. 069 265 6594, intern 955 6594
Mobil: 0173 345 53 68

--- Bitte denken Sie an die Umwelt, bevor Sie diese E-Mail ausdrucken. ---

Sitz der Gesellschaft: Frankfurt am Main
Registergericht: Frankfurt am Main, HRB 78707
USt-IdNr.: DE252204770
Geschäftsführer: Christa Koenen (Vorsitzende), Bodo Gmel, Gerald Hofer, Dr. Klaus Rüffler
Vorsitzende des Aufsichtsrates: Prof. Dr. Sabina Jeschke

Nähere Informationen zur Datenverarbeitung im DB-Konzern finden Sie hier:
https://www.deutschebahn.com/de/konzern/datenschutz

Von: tryan <notifications@github.com>
Gesendet: Donnerstag, 25. Oktober 2018 00:38
An: cubewise-code/arc-issues <arc-issues@noreply.github.com>
Cc: Olaf O Franke <Olaf.O.Franke-extern@deutschebahn.com>; Mention <mention@noreply.github.com>
Betreff: Re: [cubewise-code/arc-issues] Chore Editor deletes DST setting (#268)


Hi @OlafFranke<https://github.com/OlafFranke>,

This is a bug in the REST API (at least up to 11.3/2.0.5), the "DSTSensitive" property is ignore when updating a chore and is always set to false.

**Comment by OlafFranke** [comment]
Hi, has anyone already reported this bug to IBM? Any idea?

**Comment by cubewise-tryan** [comment]
Hi @OlafFranke,

Yep, it has been reported. Hoping for a fix soon.

**Comment by cubewise-tryan** [comment]
Hi @OlafFranke,

We have found a solution. It will be fixed in the next release.
