### ISSUE TITLE
TI created in ARC cannot open through TM1 Architect

### ISSUE THREAD

**Issue by CognosTM1** [cubewise-code/arc-issues#271]
**Describe the bug**
TI developed in ARC, does not open with TM1 architect.
Just happened to one of the process not all.

Please see attached file for screenshot:

 

**Screenshots*
Will update soon

**Desktop (please complete the following information):**
 - TM1 Version: [PA 11.2.00000.27]
 - Browser [Chrome]
 - Arc Version [1.2.0]

**Comment by cubewise-tryan** [comment]
Hi @CognosTM1,

We will need some more info. It looks like the process is empty? There isn't much information in the attachment but there is personal information, I would recommend removing that as it as this is a public site.

You can use Arc interchangeably with Architect. Can you please provide repeatable steps that cause the issue?

**Comment by cubewise-tryan** [comment]
Hi @CognosTM1,

Any update?
