### ISSUE TITLE
ARC not resetting variable names after changing view

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/arc-issues#273]
**Overview**
When changing the data source of a ti from 1 cube to another the variable names do not properly update. Resulting in minor errors. 

**Reproduce**
1)Create a TI with a cube view data source named zSample. 
2)Update variable names resulting in vVersion, vMonth, vAccount, vMeasure
3)Run TI to write data, completes okay. 
4)Change TI to point to a new cube with 1 extra dim with a view still named z Sample.
5) reset the variable names resulting in vVersion, vMonth, vAccount, ***vLocation***, vMeasure.
6) the TI looks okay but executes with a key error as if the data source variables were not updated.

If you reset the data source and variable names in Architect it fixes it.

ARC 1.2
PA 2.04

**Comment by cubewise-tryan** [comment]
Hi @rclapp,

Any update on this one?

**Comment by rclapp** [comment]
I already replied to this thread, not sure where it went. Let me see if I can find it.

**Comment by rclapp** [comment]
Not sure why this didn't go through last time.

"I used the reset variable button. I worked around the issue by doing 2 things (I wish I had done them separately now). Added a new blank variable to the list, and renamed the view so they were not the same between the new and old cubes. So I don't really know which was the fix, sorry. "

**Comment by cubewise-tryan** [comment]
Hi @rclapp,

No worries, I will close for the time being. If you find the steps we can reopen the issue.
