### ISSUE TITLE
Search behaviour is extremely slow

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#276]
**Describe the bug**
There is a long delay (sometimes multi-second) when typing in the search box above the server/object tree. 

**To Reproduce**
Be logged into several large instances with control objects displayed (such that the overall object list is several thousand items). Enter a filter and contains wildcard in the search box (e.g. "t:c CRM"). The text entry response is extremely laggy as the browser filters the list on each keystroke. 

**Expected behavior**
Allow a 1 second delay after last keystroke before executing the filter. This will allow users to enter text without being held up by the filter continually re-triggering. If this is not possible even only triggering the filter on enter key or search input box losing focus would be preferable to current behaviour.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - TM1 Version: 11.3
 - Browser Chrome, Edge
 - Arc Version 1.2.0

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

The search is already waiting for 500ms of inactivity before searching. We have added an option to set that to what ever you want but will default to 1000ms and a second parameter for the minimum number of search character to the About page. By default it is 3.
