### ISSUE TITLE
Arc searches for TM1 objects in previously connected servers

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#277]
**Describe the bug**
Arc searches for TM1 objects in instances which aren't available.

**To Reproduce**
1. Connect to a specific TM1 instance, let's say "Planning Sample"
2. Stop the "Planning Sample" instance and refresh Arc (don't refresh browser, just Arc using the refresh button next to the search box).
3. Connect to another instance which is available, for example "SData"
4. Search for some object which could be found in both instances.
5. Although Planning Sample is offline you can see that Arc displays results from previously available instances
6. See the images for details.

**Expected behavior**
Arc should only search within the currently connected TM1 instances.

**Screenshots**
![image](https://user-images.githubusercontent.com/39726565/47557871-10d78a80-d912-11e8-9f63-ace46287fae4.png)

---
![image](https://user-images.githubusercontent.com/39726565/47557856-04ebc880-d912-11e8-86b8-8ba260e3931f.png)

**Desktop (please complete the following information):**
Arc version 1.2.0
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor,

Arc doesn't know that the instance is offline so there is not way for it to stop the search. The menu list is stored in the browser and can be used over multiple restarts. One of the benefits of having it this way is that you can edit/save over multiple sessions or even restarts.

**Comment by RaduCantor** [comment]
@cubewise-tryan well I understand the benefits of this, but I think that Arc should only search in the active instances and not in the whole list.

I think that Arc is aware of the available instances, since it only displays the ones which are accessible in the list. I think Arc should know that even thought it was connected to a specific TM1 instance, if that instance is no longer in the menu list then most likely it's not available.

In my example it's not only the instance which isn't available, but the entire server.

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor,

Arc is only aware of the avaible instances when you refresh the browser or click the refresh icon.

I can see the issue, when the refresh icon is pressed the search data isn't cleared when the menu is. That will be fixed.
