### ISSUE TITLE
Process editor character encoding issue

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#280]
**Describe the bug**
The latest version of Arc doesn't encode some ASCII characters correctly. This results in corruption of TI processes edited with Arc.

**To Reproduce**
Open TI process in Architect. Include some string variables commonly uses as delimiters. e.g. ¦ | : ;
Save the process
View the .pro file in Notepad
Open the process in Arc. Save the process
View the .pro file in Notepad

**Expected behavior**
Characters should not be corrupted when editing with Arc

**Screenshots**
.pro file viewed in Notepad before editing in Arc
![image](https://user-images.githubusercontent.com/29408388/47644701-2a294280-db6f-11e8-99a0-2b8817b2188c.png)
how the text looks in Arc
![image](https://user-images.githubusercontent.com/29408388/47644718-34e3d780-db6f-11e8-9e0e-5758f83e0524.png)
After saving in Arc what the .pro file looks like
![image](https://user-images.githubusercontent.com/29408388/47644738-47f6a780-db6f-11e8-8375-ad12ce127f08.png)
Ammend in Arc to what the correct character should be
![image](https://user-images.githubusercontent.com/29408388/47644784-68266680-db6f-11e8-8bcb-dd5588b57786.png)
After saving in Arc what the .pro file looks like
![image](https://user-images.githubusercontent.com/29408388/47644853-95731480-db6f-11e8-908b-3791465fdb2f.png)

**Desktop (please complete the following information):**
 - TM1 Version: 11.3.000031
 - Browser Chrome
 - Arc Version 1.1.2

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

Can you please provide a sample snippet of the code or a pro file so we can test.

**Comment by lotsaram** [comment]
Here's the snippet where I noticed the issue. This process was last saved in Arc, which version I'm not sure, but about 1 month ago.
`# if pDimension is a dimension with hierarchies (not a leaf alternate hierarchy) then view will contain the leaf hierarchies
sProc           = 'Bedrock.Cube.View.Create';
sFilter         = cDimSrc |'¦'| pDimension |'&'| cDim4 | '¦Final Value';
bSuppressNull   = 1;
bSuppressC      = 0;
bSuppressRule   = 0;
ExecuteProcess( 	sProc,
	'pCube', cCubSrc, 'pView', cViewSrc, 'pFilter', sFilter,
	'pSuppressZero', bSuppressNull, 'pSuppressConsol', bSuppressC, 'pSuppressRules', bSuppressRule,
	'pDimensionDelim', '&', 'pElementStartDelim', '¦', 'pElementDelim', '+',
	'pDebug', nDebug 
);`

If I try and re-create the same from scratch now using 1.2.1 I don't get the same issue.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

I can't repeat this, the characters work fine in my tests. Can you try another browser? It seems to be an issue with the charset. Arc uses UTF-8 which supports all characters, it seems to be an issue with the browser or TM1.

**Comment by cubewise-tryan** [comment]
You could also check to see the content being returned and sent to TM1 on the network tab of the Chrome Developer Tools (F12).

1. Click on the network request for the process
1. The Headers tab has the data sent.
1. The Response tab has the data returned

![image](https://user-images.githubusercontent.com/22929868/47848736-6684c900-de23-11e8-8e17-a7b9fcfade6e.png)

**Comment by lotsaram** [comment]
I have opened the same process in edge and get the same result. The character causing the issues is "broken bar".
Html Entity: &brvbar
Hex: &#xa6
Decimal: &#166

In the saved version of the process I can see the "¦" character which returns code 166. In the response from the server however it comes back as question mark spanning 2 characters. I will link the process as maybe that's the only way to reproduce. Maybe something weird has happened with the character encoding in the original creation in Architect or a previous edit in Arc. If I save the process replacing the question mark with broken bar then although the .pro file doesn't look any different in a text editor the issue doesn't reoccur.

Here's the link to the process. [https://www.dropbox.com/s/cvp8zoji30xucop/%7DAPQ.Dim.Attr.Definition.Update.pro?dl=0](url)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

This is an issue in the TM1 REST API. The question mark you see is actually the unicode replacement character and that is what TM1 is sending. The same character is returned in Arc and Postman. We will contact IBM and see if it can be solved.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

I have found a workaround of sorts, the file is encoded with ANSI. You can convert this to UTF-8 which is what the REST API uses in Notepad++. Save and then restarting the server will replace the special character.

![image](https://user-images.githubusercontent.com/22929868/48612924-6f0dff80-e9de-11e8-8074-4e1acdb7429d.png)

**Comment by lotsaram** [comment]
Thanks! Good to know.
