### ISSUE TITLE
Search in Subset Editor results in error

### ISSUE THREAD

**Issue by daniella003** [cubewise-code/arc-issues#281]
Searching for elements in the Subset Error results in an MDX error

**To Reproduce**
1. From Cube Viewer, Open Subset Editor for a dimension
2. Click on "All"
3. Click on the search box and type a string contained in several element names
4. Error "Could not execute MDX expression. Unknown error" appears
(The second screenshot shows that elements with that string exist in the dim)

**Expected behavior**
Typing a string in the search box would return all elements that contain that string in their names

**Screenshots**
![image](https://user-images.githubusercontent.com/36972576/47677627-03cacd80-db96-11e8-88aa-36a7378dccb3.png)
![image](https://user-images.githubusercontent.com/36972576/47677636-09281800-db96-11e8-893b-b9194a3c15a9.png)

**Desktop (please complete the following information):**
 - TM1 Version: 2.0.5
 - Browser:  Chrome
 - Arc Version 1.2.0

**Comment by cubewise-tryan** [comment]
Hi @daniella003,

Can you please try 1.2.1 (https://code.cubewise.com/arc-download/). That is related to issue #269.

**Comment by daniella003** [comment]
Yes, it seems to be resolved in 1.2.1. Thanks!
