### ISSUE TITLE
Backout From Transaction Log

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/arc-issues#283]
**Is your feature request related to a problem? Please describe.**
Currently when we have made some mistake on data processing, we will need to go back to Perspective/Architect in order for us to back out the data, would be nice if we can use Arc to do back out as well.

**Describe the solution you'd like**
On Tools, we have the option to do Back Out, and also a screen for us to browse/search Transaction Logs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cubewise-tryan** [comment]
Hi @tatwong,

This isn't something we plan to add to Arc as its primary use is a development tool. We have had similar requests for Pulse and we may look at adding it there.
