### ISSUE TITLE
Display Name still show CAM ID in Administration/Security

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/arc-issues#284]
**Describe the bug**
Unable to read the display name of an user, unable to search.

**To Reproduce**
1. Go to Administration/Security

**Expected behavior**
Show Display Name of the CAM User.

**Screenshots**
![image](https://user-images.githubusercontent.com/43463864/47699757-ee65aa00-dc4e-11e8-830e-b1b0f37c2d4b.png)

**Desktop (please complete the following information):**
 - TM1 Version: 10.2.2
 - Browser IE 11
 - Arc Version 1.2.1

**Additional context**
N/A

**Comment by cubewise-tryan** [comment]
Hi @tatwong,

We are actually showing the "FriendlyName" from the REST API which is the name with special characters removed. The REST API doesn't return the Display Name you see in the }Clients dimension.

We can can the query so it retrieves the alias from the }Clients dimension.
