### ISSUE TITLE
Rule Syntax Highlight issue for Dimension References with Underscore

### ISSUE THREAD

**Issue by strangiato** [cubewise-code/arc-issues#29]
When writing a rule that uses a reference to a dimension (e.g. !DimensionName) the syntax highlighting will stop after after an underscore.

See the screenshot below for an example:

![image](https://user-images.githubusercontent.com/1628206/38040818-f7d9f56a-3275-11e8-9c2f-27301c9433ff.png)

**Comment by cubewise-tryan** [comment]
Fixed, it now also supports non-ASCII characters as well as underscore.
