### ISSUE TITLE
Upgrade procedure (question)

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/arc-issues#290]
Can you please confirm whether my assessment is correct?

If I want to install newer version and want to avoid that I loose own templates and plugins:
[1] Copy arc..exe from new to old
[2] Copy plugins folder from new to old and either 
[a] include plugins.yml from new and add own plugins manually
[b] exclude plugins.yml and add any additional plugins from new version manually

**Comment by cubewise-tryan** [comment]
Hi @hermie64,

1. Stop the Arc Windows service or executable
1. Replace the arc.exe with the new one.
1. Start the Windows service or double click on arc.exe

Settings and templates shouldn't be overridden, let us know if they are. Any of the built-in plugins are overwritten when a new version is installed. If you want to modify a plugin create a new one by copying the folder and renaming the plugin in plugin.js:

![What to update](https://user-images.githubusercontent.com/22929868/47939076-2d8b4800-df3a-11e8-8048-3ceb4a8848b1.png)
