### ISSUE TITLE
Title elements are listed on row, when there is no row dimension in a cube view

### ISSUE THREAD

**Issue by muhammedalionder** [cubewise-code/arc-issues#291]
**Describe the bug**
When there is no dimension on the row of a cube view, all title elements are listed on the row of cube view.

**To Reproduce**
1. Go to any cube view
2. Prepare a cube view without any dimension on row
3. Execute the view
4. See title elements are listed on row

**Expected behavior**
There should not be any row element, because we did not put any dimension on row.

**Screenshots**
![image](https://user-images.githubusercontent.com/19662602/47984795-fd79ab80-e0d7-11e8-93f6-2148681bf0f8.png)

**Desktop:**
 - TM1 Version 11.3
 - Chrome Version 70.0.3538.77 (Official Build) (64-bit)
 - Arc Version 1.2.1

**Comment by cubewise-tryan** [comment]
Hi @muhammedalionder,

This REST API adds the titles elements to the axes when the rows are missing. Not sure if that is intended behavior or not but we will follow up with IBM.

**Comment by cubewise-tryan** [comment]
Hi @muhammedalionder,

This is the intended behavior of TM1, if there is no row dimension the titles elements are added in their place.
