### ISSUE TITLE
Chore - Arc schedules the chore at the wrong time

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#292]
**Describe the bug**
Arc will not schedule the chore at the right time. This is especially bad if you are trying to schedule a chore close after midnight, and you are using the Bedrock.Chore.DayOfWeek.Run process in order to control the day when the chore should run.
In my example, both the server and my local computer are on the same time zone.

**To Reproduce**
1. Schedule any chore in Arc
2. Open the same chore in Architect
3. Notice that in Architect, the chore is scheduled 1 hour earlier (local time).

**Screenshots**
![image](https://user-images.githubusercontent.com/39726565/47999356-ab9a4b00-e102-11e8-974f-9f1e6f318aee.png)

![image](https://user-images.githubusercontent.com/39726565/47999373-b9e86700-e102-11e8-8597-51627e90866f.png)

**Desktop (please complete the following information):**
Arc version 1.2.1
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor,

Arc doesn't have any logic to set the time, it only provides the REST API with the local time you see on the chore page and then TM1 handles updating the chore. I have tried it and I don't get the same issue, the time is correct for me.  My guess is that it may be related to the recent change in DST.

**Comment by RaduCantor** [comment]
Hi @cubewise-tryan 
I did a few more tests, and I think this has more to do with the time zone in which the chore was created. This is independent of the "Run Chore time in" attribute, as Arc doesn't set that one properly.

If I create a chore now, it will display correctly, as both my computer and the server are using the CET (UTC+1) time zone.

However, if today I open a chore in Arc, that was created by Arc in a different time zone (for example during the summer time CEST = UTC+2), then Arc will still display the time, as it was created, but Architect will adjust the time to the timezone.
So, a chore that was created in UTC+2  and was scheduled to run every Saturday at 00:05, will still show as being scheduled for Saturday 00:05 in UTC+1. However, the same chore in Architect will display as scheduled to run on Friday at 23:05. And it will actually run on Friday at 23:05, instead of Saturday at 00:05.

So I still think there is something different (or wrong) in the way Arc sets or gets the scheduled time. Personally, I think that Arc does it the right way, but apparently Architect disagrees, and the chore runs as displayed in Architect.

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor,

I have done some more investigation and the key part is the date you use. If you set the date to when day light savings was the opposite to the current status it will move by one hour as TM1 always stores the time in UTC. To fix this use the DST Sensitive property which we have fixed and will be in the next version. See this ticket: #268
