### ISSUE TITLE
Can't close Frameworks tab

### ISSUE THREAD

**Issue by uttergithub** [cubewise-code/arc-issues#293]
**Describe the bug**
Minor issue: When clicking on the Frameworks item under Administration, it opens a new window to Bedrock Github page. Ok, but it also opens a new tab called Frameworks which cannot be closed (and has nothing in anyway).

[Another minor issue: My name is uttergithub and I am an Arcaholic. Can't stop playing with the damn thing. Suggestions?]

**Desktop (please complete the following information):**
 - TM1 Version: 11.1
 - Browser: Chrome & Safari
 - Arc Version:1.2.1

**Comment by cubewise-tryan** [comment]
Hi @uttergithub,

Is Frameworks a plugin? That isn't one of the standard admin items. 

As for being an "Arcaholic" sufferer, unfortunately it is an incurable condition, it is best to just embrace it.    

![image](https://user-images.githubusercontent.com/22929868/48039722-372adf00-e1ca-11e8-96cf-5ec1d7b5e9d8.png)

**Comment by uttergithub** [comment]
Ah yes, my bad. Foreign code!
