### ISSUE TITLE
Previewing Cube View returns error

### ISSUE THREAD

**Issue by psegal** [cubewise-code/arc-issues#294]
**Describe the bug**
Preview of cube view for TI process returns internal server error out of memory (see screenshot). 

**To Reproduce**
1. Create new process
2. Select TM1CubeView
3. Select Cube
4. Select View
5. Click Preview
6. See error

**Expected behavior**
Correct Result

**Screenshots**
![arcsystemerror](https://user-images.githubusercontent.com/27949728/48071505-65acb800-e1d2-11e8-8cea-3eb7fcb70697.png)

**Desktop (please complete the following information):**
 - TM1 Version: 11.2.00000.27
 - Browser Firefox, Vivaldi
 - Arc Version 1.2.1

**Additional context**
It's a standard view rather than MDX, if that should make a difference.

**Comment by cubewise-tryan** [comment]
Hi @psegal,

Unfortunately this isn't something we can fix in Arc. Arc already limits the result through the REST API but the server is constructed on the server causing an out of memory error.  We have already passed this on to IBM 

#169
