### ISSUE TITLE
Show memory used in cubes & dimensions info pannels

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#298]
**Is your feature request related to a problem? Please describe.**
In Arc you can't see the memory consumption by cube. Especially now the rest API supports re-ordering of dimensions in a cube as a developer you should be able to see this easily.

**Describe the solution you'd like**
The cubes info panel should display the total memory used by cube after the cube name. The table should be sortable on this column.

**Describe alternatives you've considered**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/29408388/48354615-7063c300-e692-11e8-98fe-9c3dc833b7ab.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

The memory per cube (or any memory reading) is not available through the REST API and from what I have been told it is not planned. We will possibly look at this when we add integration with Pulse.

**Comment by lotsaram** [comment]
OK. 

> The memory per cube (or any memory reading) is not available through the REST API and from what I have been told it is not planned.
That I must say sounds bizarre. How can you have a cube re-ordering functionality without being able to see the before and after effect on memory?!?

**Comment by PiotrRajtar** [comment]
Hi @lotsaram,

The re-ordering functionality only returns a relative percentage change for a given order (e.g. -50%) - so it can still be used for its purpose similar to what the Architect re-ordering tool did.

But the lack of access to memory per cube is a bit disappointing. I guess that a workaround could be using }StatsByCube or Pulse integration going forward.
