### ISSUE TITLE
add keyboard accelerator keys for toggle comment

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#3]
All buttons on the edit toolbar have an accelerator key combination except for "toggle comment" which can only be activated by clicking on the button.  Ctrl + / is the most commonly used shortcut for toggle comment, this would therefore be a logical choice.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

The Ctrl + / shortcut has been added for rules and processes.
