### ISSUE TITLE
ARC variables are assigned to wrong dimensions

### ISSUE THREAD

**Issue by 4rtem** [cubewise-code/arc-issues#30]
Hi guys,

We have an issue when ARC is assigning wrong dimension elements to wrong variables using CubeView as the source. Probably it happens when you change DataSourceCubeView in the prolog.

Scenario:

1.	Create a TI, using Cube View/Default as the data source
2.	Put similar logic in Prolog relevant to that View:

_pView='Test';

EXECUTEPROCESS('Bedrock.Cube.ViewAndSubsets.Create',
  'pCube', 'L4L',
  'pSuppressZero', 1,
  'pSuppressConsol', 1,
  'pSuppressRules', 1,
  'pDimensions', '',
  'pDelimiter', '&',
  'pView', 'Test',
  'pSubset', '',
  'pDebug', 0
  );
  
EXECUTEPROCESS('Bedrock.Dim.Sub.Create.Leaf',
  'pDimension', 'Calendar Season',
  'pSubset', 'Test',
  'pAddToSubset', 0,
  'pExclusions', '',
  'pDelimiter', '&',
  'pAlias', '',
  'pDebug', 0
  );
  
  EXECUTEPROCESS('Bedrock.Dim.Sub.Create.Leaf',
  'pDimension', 'Cluster',
  'pSubset', 'Test',
  'pAddToSubset', 0,
  'pExclusions', '',
  'pDelimiter', '&',
  'pAlias', '',
  'pDebug', 0
  );
  
  EXECUTEPROCESS('Bedrock.Dim.Sub.Create.Leaf',
  'pDimension', 'L4L Product',
  'pSubset', 'Test',
  'pAddToSubset', 0,
  'pExclusions', '',
  'pDelimiter', '&',
  'pAlias', '',
  'pDebug', 0
  );

  EXECUTEPROCESS('Bedrock.Dim.Sub.Create.Leaf',
  'pDimension', 'L4L m',
  'pSubset', 'Test',
  'pAddToSubset', 0,
  'pExclusions', '',
  'pDelimiter', '&',
  'pAlias', '',
  'pDebug', 0
  );_

  DatasourceCubeView='Test';

3.	Add Just one test line in Data:

v=CellGetN('L4L', vCalendarSeason, vCluster, vL4LProduct, vL4Lm);

4.	Save the TI,  Run it. It completes without errors.

5.	Try to change variables order or just click Preview in the data source

6.	The TI will generate error  saying that  that dimension elements values are assigned to wrong variables.
![image](https://user-images.githubusercontent.com/37865391/38043712-2ac1acec-32b8-11e8-8cb3-70d5b7b02625.png)

It’s pretty annoying, because the only way to fix such TI is to go to Architect and update variables there.
Feel free to contact if you cannot reproduce that.

Thanks!

**Comment by cubewise-tryan** [comment]
Hi @4rtem, 

The order of the elements is determined by TM1 and depends on where the dimensions are placed in the view, i.e. on rows, columns and titles. When the process is run it just sets the variable according to its location (1, 2, 3, etc) not its name.

After previewing and replacing the variables does it work?

**Comment by 4rtem** [comment]
No, it does not work after previewing and replacing variables.  But anyway switching TI datasource  to the other view in the prolog is a common thing and it should not affect matching variables with the correct dimensions ... TI actually stops to work after I preview and replace the variables. Thanks.

**Comment by cubewise-tryan** [comment]
Hi @4rtem,

I have tried a few things and I don't understand what the issue it. You shouldn't reorder variables unless the view is different. There is no matching of variables, the order in which they are returned from the view is how they are inserted into the variables.

**Comment by 4rtem** [comment]
Hi Tim, I was on holidays and did not reply to you.
I will give more information as we are struggling from that, maybe record a short screen capture video.
Thanks.

**Comment by cubewise-tryan** [comment]
Sounds good.

**Comment by 4rtem** [comment]
@cubewise-tryan 

I have not seen that for a while.
But it looks that in 0.9.7 the problem still exists.

![image](https://user-images.githubusercontent.com/37865391/40417077-3145bc78-5e7f-11e8-99dd-b21acdb691bb.png)

**Comment by cubewise-tryan** [comment]
Hi @4rtem,

Are the steps to reproduce the same as before? Can you please check if that is the case.

**Comment by 4rtem** [comment]
Hi Tim,
Yes, you can use same scenario to reproduce the problem, I've just tested in 0.9.7

**Comment by 4rtem** [comment]
Hi guys,
Any update on this?

**Comment by cubewise-tryan** [comment]
Hi @4rtem,

I have tried again and it works fine for me. Have you regenerated the variables. Check that the position

**Comment by Sneb85** [comment]
Hi @cubewise-tryan 

I'm using arc 0.9.7 with TM1 10.2.2 FP7 at a client and it seems the order issue is still happening. When I save the TI via Arc, the variable position is reset. See screenshots below

![image](https://user-images.githubusercontent.com/38934704/42148921-6c512264-7e17-11e8-92bf-f2ca5cf906df.png)

![image](https://user-images.githubusercontent.com/38934704/42148936-7acb24d4-7e17-11e8-9b86-7b5d676a46d0.png)

**Comment by cubewise-tryan** [comment]
Hi @4rtem & @Sneb85 ,

We have found the source of this issue, the Position property was being updated when loading an existing processes and then saving. This was overriding the correct value that was set with "Replace Variables"
