### ISSUE TITLE
Debugger Prevent to switch process tab

### ISSUE THREAD

**Issue by grandryjn** [cubewise-code/arc-issues#301]
**Describe the bug**
When debugging I can't go to another process tab. The focus bring back to the TI being debugged.

I originally wanted to debug 2 TI at the same time to analyse locks, a work around has been to open another Chrome Tab to have 2 debug session at the same time.

**To Reproduce**
1. Open 2 processes
2. Start debugging on one of the process
3. Click on the other process tab
4. After 1 or 2 second the focus is made back to the process being debugged.

**Expected behavior**
Stay on the process that has been clicked on.

**Desktop (please complete the following information):**
 - TM1 Version: 11.4
 - Browser: Chrome 
 - Arc Version: 1.2.1

**Comment by cubewise-tryan** [comment]
Hi @grandryjn,

This is the intended behavior, it works this way so that you switch tabs when step into another process. The work around as you say is to open another browser tab/window.
