### ISSUE TITLE
Arc in dev, qa and prod environment (question)

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/arc-issues#303]
**Is your feature request related to a problem? Please describe.**
What is your recommendation to use Arc in dev, qa and production setup where instances have the same names?
If I connect via Chrome to admin host A, open a second tab or session of Chrome to connect to admin host B and change the admin host via "Admin Hosts" button also the "Admin Hosts" in first Chrome tab/session are affected.

**Describe the solution you'd like**
Maybe I missed something in the setup or maybe this is currently not possible (if so, maybe add Admin Host as parent in Arc tree?).

**Describe alternatives you've considered**
I can only make this work if I use another web browser.

**Comment by cubewise-tryan** [comment]
Hi @hermie64,

You should have a separate Arc for each server. The alternative is to connect to each instance using the connections option in settings.yml. You can set an name/alias for each instance.
