### ISSUE TITLE
Improved behaviour of tab stubs when multiple tabs are open

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#305]
**Problem description**
In Arc the tab captions are quite long. Process names are themselves usually long anyway but because the instance name is included first and for hierarchy editor and cube viewer the caption is instance:dimension/hierarchy and instance:cube/view respectively the tab captions are often very long. This means that even on a ultra high res widescreen monitor you typically only need 2 at most 3 tabs open at the same time before tabs start being "un-tabbed" and moved to the hidden tabs list where they are no longer as readily accessible.

**Describe the solution you'd like**
Before tabs are hidden from view the size of all active tabs should first be reduced like it is handled in most internet browsers. If tabs stayed visible with only the full name on the focus tab and just the tab stub visible for other tabs with full caption text visible via tooltip hover this would be a better solution.

**Describe alternatives you've considered**
Tab spinner < > buttons rather than dropdown list of hidden tabs.

**Additional context**
Currently even on high res monitor after 3 active tabs you end up with tabs being hidden. Here 4 tabs are open and already one is hidden.
![image](https://user-images.githubusercontent.com/29408388/48625486-aca76400-e9af-11e8-81bb-85831041106d.png)
Compressing tabs to stubs with full caption displaying as tooltip text on hover (just like Chrome & Firefox do it) would be better.
![image](https://user-images.githubusercontent.com/29408388/48625539-d6f92180-e9af-11e8-8fcb-790f3d9ef45c.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

We use a third-party library for the tabs so changing the behaviour would take quite a bit of work. I think it is better if we focus out time elsewhere. The screenshot you have provided looks great but isn't going to work for Arc as the icons are going to be similar. You will then need to hover over each one to see what it is.

You can either use the tab drop down on the right or the last used items in the menu to navigate between tabs. 

Not sure the size of your "high-res" screen but if you have only 3 tabs visible you have some very long names!

**Comment by lotsaram** [comment]
Same screen as yours @cubewise-tryan 2k x 3k with chrome on 90% scaling.
