### ISSUE TITLE
Global find/replace

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#307]
**Is your feature request related to a problem? Please describe.**
Sometimes there is a need to perform a global find/replace on a TM1 model. e.g. due to name change of object, change to dimensionality of cube, etc.

**Describe the solution you'd like**
It would be very useful if Arc supported a global find/replace for text within rule and process files.

**Describe alternatives you've considered**
Notepad++ find in files feature. Windows Powershell. 
However, any method which requires restart of model is inferior to doing live code change.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

This would require pulling every TI and rule from the server to first find and then replace. It would also be very slow. You are better off doing it in the files or we could look to add this a a feature of Pulse as it has a local copy on the code.
