### ISSUE TITLE
Read only version

### ISSUE THREAD

**Issue by brianknott** [cubewise-code/arc-issues#309]
Not sure if its possible but a read only version of rules TI etc would be very hand.  We don't want the ability to change rules and TI's in production but is would be great to be able to view then and cut and paste to a development version.

Brian

**Comment by cubewise-tryan** [comment]
Hi @brianknott,

The answer to that would be change the security of the cube and not have admin account on production. Setting the rule editor to read-only would only lock the UI. When we have integration with Pulse that will allow you to migrate files to prod from Arc.
