### ISSUE TITLE
Default behaviour of CubeName click

### ISSUE THREAD

**Issue by jgorsk** [cubewise-code/arc-issues#314]
**Is your feature request related to a problem? Please describe.**
For some time rule editor was default action when clicking on CubeName. Arc is by definition developer tool and 90% of cases when I click on Cube I want to edit rule, not see Cube Viewer.

**Describe the solution you'd like**
Parameter in configuration of Arc that sets default action after clicking Cube Name - Rule Editor or Cube Viewer.

**Comment by hermie64** [comment]
+1

**Comment by cubewise-tryan** [comment]
Two new options will be available in v1.3.0:
![image](https://user-images.githubusercontent.com/22929868/48923586-00f89980-ef04-11e8-810d-119b3465b33a.png)
