### ISSUE TITLE
TM1 Instance Crash when using Administrator session : tm1 version :10.2.20705.73 

### ISSUE THREAD

**Issue by IA-cube** [cubewise-code/arc-issues#315]
**Describe the bug**

Hi 
I was using ARC for developping, executing an export processus, and i also use the adminstration session.
When i launched the export process , then it took too long to execute:
So i opened the administration /session in ARC to see what's happening : i was in "wait" status, then i tried to cancel my thread, and saved my processus and after a few minutes the Instance crashed ( it happend two times).

Here's  the TM1 log server : 

  | 28172     [79]   ERROR   2018-11-21 09:32:36.072     TM1.Process   Process "z_Export_Cube_v3_to_v4_format": :   Execution was aborted. Error file:   <TM1ProcessError_20181121093235_36928172_z_Export_Cube_v3_to_v4_format.log>   : File   "\\shtm1str-na.sanofi.com\sh_tm1_amer\TM1Models\TM1NA\Uploads_NA\test\NA_OPX_OpEx_2018_LRP1_F2_USA_Base_LOGS.csv"   not found.
-- | --
  | 28172     []   ERROR   2018-11-21 09:43:03.519     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  
  | 5820     []   ERROR   2018-11-21 09:43:07.128     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  
  | 9284     []   ERROR   2018-11-21 09:44:19.744     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  
  | 15184     [79]   INFO   2018-11-21 09:44:20.853     TM1.Process   Process "z_Export_Cube_v3_to_v4_format"   executed by user "AD/Al-Othman, Mohamed _FR_EXT"
  | 15184     [79]   INFO   2018-11-21 09:44:20.853     TM1.Process   Process "z_dim.update_Mapping_v3_to_v4" run   from process "z_Export_Cube_v3_to_v4_format" by user   "AD/Al-Othman, Mohamed _FR_EXT"
  | 19552     []   ERROR   2018-11-21 09:45:08.670     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  
  | 18796     []   ERROR   2018-11-21 09:45:27.656     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  
  | 23724     []   ERROR   2018-11-21 09:45:34.391     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  

**To Reproduce**
1. open Arc and  Execute a processus 
2. If it take too long, then open the admin session
3. If the process is in wait status, try to save it and cancel it 
3. Repeat these actions several time( try to cancel or save the processus)

**Expected behavior**

 The Instance should crash, and the following error message wil appear to the tm1server logs : 
  | 19552     []   ERROR   2018-11-21 09:45:08.670     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  
  | 18796     []   ERROR   2018-11-21 09:45:27.656     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  
  | 23724     []   ERROR   2018-11-21 09:45:34.391     TM1.NGAPI.REST   deflateEnd error: CODE: -3 MSG: null |  
**Screenshots**

**Desktop (please complete the following information):**
 - TM1 Version: 10.2.20705.73 
 - Browser  Chrome
 - Arc Version: 1.1.0

**Additional context**

Thank you  for your help

Best Regards

**Comment by cubewise-tryan** [comment]
Hi @IA-cube,

This seems to be a bug in TM1 rather Arc. Not sure of the cause but we will pass on the details to IBM
