### ISSUE TITLE
Process description in process list

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/arc-issues#316]
**Is your feature request related to a problem? Please describe.**
Purely an enhancement request improving life of a TM1 developer.

**Describe the solution you'd like**
I would like to see an additional column with process description (custom and editable) in list of processes.

**Describe alternatives you've considered**
None.

**Additional context**
I thought about two possible solutions:
1. Use an existing metadata property of process to store such description
2. Store process description inside process e.g. prolog tab, between start and end string markers (like #Region and #Endregion, but something specific for this functionality e.g. #DescriptionRegion #EndDescriptionRegion) and then display a result of query looking for a string between such markers.
 If this works, then it could also be used for cubes.

**Comment by lotsaram** [comment]
Hi @macmaj 
This feature is already there in Pulse so pretty sure the answer will almost certainly (and rightly) be that this will come with Pulse integrations.

**Comment by cubewise-tryan** [comment]
Hi @macmaj,

Yep, @lotsaram has the answer, when we integrate with Pulse this will be available but not with Arc alone.

**Comment by macmaj** [comment]
Hi @lotsaram and @cubewise-tryan,

Thanks for the answer. 
I hope the integration comes sooner than later.
