### ISSUE TITLE
MDX query tool - not showing meaningful errors

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#318]
**Describe the bug**
When MDX set expression has errors, Arc doesn't show meaningful errors.

**To Reproduce**
1. Open the MDX query in Arc, and write a MDX set query that contains errors
2. Check the error provided by Arc
3. Execute the same query in Architect
4. Notice the proper error message in Architect

**Expected behavior**
Arc should provide meaningful error messages. Please see the images for comparison.

**Screenshots**
![image](https://user-images.githubusercontent.com/39726565/49016403-46c49480-f186-11e8-999d-0508c89d1b50.png)

![image](https://user-images.githubusercontent.com/39726565/49016384-38767880-f186-11e8-839a-8cd21c5c591a.png)

**Desktop (please complete the following information):**
Arc version 1.2.1
TM1 version 11.1.00000.30
Browser Chrome / Firefox / Edge

**Comment by cubewise-tryan** [comment]
Hi @RaduCantor,

This is a limitation of the REST API not Arc. If you check out the response in the browser developer tools you will see that is what is returned by TM1:

![image](https://user-images.githubusercontent.com/22929868/49049151-e723c300-f231-11e8-8d29-00010c2ea86e.png)

We will send the details through to IBM
