### ISSUE TITLE
Connecting to cloud instance

### ISSUE THREAD

**Issue by CJRothman** [cubewise-code/arc-issues#319]
I have a client that uses PA in the cloud but I am not sure what the url of the Admin Host is to set up in my settings.yml file. The Admin host in Architect options is just 'Data'

**Comment by cubewise-tryan** [comment]
Hi @CJRothman,

You need to connect directly to the REST API using the `connections` option in Arc. You can also remote desktop into the admin environment and connect to the admin host that way.

The steps to use Arc with the IBM Cloud are as follows. The instructions are based on using TM1 security mode 5 (the default):

1. Upload the Arc executable to your **Remote Desktop System**. The easiest way to do this is to use FTP upload facility.  
1. Create a folder named **Arc** in your **Documents**
1. Save **arc.exe** to **Documents\Arc**.
1. Double-click on the **Arc** executable to start the Arc server.
1. Open **settings.yml** in Wordpad and change the admin host from `https://localhost:5898` to `https://data:5898`
1. Save **settings.yml**
1. Navigate to the http://localhost:7070
1. Go to the About page of Arc (top right icon) and tick **TM1 Credentials** > **Store Credentials**.
1. Click on your TM1 instance to login, you need to use the TM1 automation credentials provided in your welcome pack:
   * **CAM Namespace**: LDAP
   * **User Name**: `customername`_tm1_automation
   * **Password**: password provided by IBM

After you have logged in you will need to add the TM1 automation user to the Admin group if it hasn't been added already. To do this:
1. Login in to Architect with your IBM Id
1. Right-click on the server: Security > Clients/Groups
1. Find the TM1 automation user and tick the Admin group box.
1. Close the browser and log back into Arc.

**NOTE**: The alternative to using the TM1 automation credentials is to change TM1 to security mode 1

**Comment by CJRothman** [comment]
So you are saying for cloud customers we have to be logged onto the remote server in order to use ARC. We can't use ARC from our lap top.

**Comment by cubewise-tryan** [comment]
Hi @CJRothman,

You can use it from your laptop, to do that you need to set the external URL to the REST API. It looks like the link below. You need to replace the **server** name with the correct one.

https://**server**.planning-analytics.ibmcloud.com/tm1/api/tm1
