### ISSUE TITLE
Menu search does not work for long object names

### ISSUE THREAD

**Issue by PiotrRajtar** [cubewise-code/arc-issues#32]
It seems that the menu search does not search in the latter parts of long process names:
![image](https://user-images.githubusercontent.com/32559614/38060136-20c0ad2e-3335-11e8-8988-de792ec62eb9.png)
![image](https://user-images.githubusercontent.com/32559614/38060149-38711e7c-3335-11e8-9a7a-b4cee66e88a0.png)

**Comment by cubewise-tryan** [comment]
Arc is using a fuzzy search, we plan to change this to a simpler 'contains'. That will fix this issue.

**Comment by cubewise-tryan** [comment]
Fix will be in the next release
