### ISSUE TITLE
Menu/objects - Mark Rule/Process as being edited 

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/arc-issues#323]
**Is your feature request related to a problem? Please describe.**
On bigger projects, with more developers, it's not uncommon that more than one person works on rules for one cube. If developers are unaware of that then they might accidentally overwrite their work.

**Describe the solution you'd like**
Some kind of a binary flag, next to objects name (rules in a cube or a process), marking if rule/process is being edited. Handling of this flag would be purely manual and would require developers to click on it to change it's state (Yes, being edited/No, not being edited). 
This information could be stored in a REST API metadata filed (if something like that exists) or in a Arc parameters cube (something like that currently doesn't exist, but I think having such cube could be beneficial in more situations and it could be an **optional** functionality requiring users to run a process building an additional system cube in their model. That means it wouldn't change Arcs idea of being a fully standalone application).

**Describe alternatives you've considered**
No alternatives inside Arc and easily visible to developers.

**Additional context**
None.

**Comment by cubewise-tryan** [comment]
Hi @macmaj,

This is planned for the enterprise version when integrated with Pulse.

**Comment by 4rtem** [comment]
It would be great to have, maybe it is better to have not binary flag, but name of the developer who took the ownership on the object.
