### ISSUE TITLE
Specific TM1 functions not appear in intellisense

### ISSUE THREAD

**Issue by RaduCantor** [cubewise-code/arc-issues#329]
**Describe the bug**
Functions such as ```SubsetElementGetIndex```, ```ElementAttrPutS``` and ```ElementAttrPutN``` don't show up in intellisense. Potentially there could be other functions with this situations.
I already raised this here: https://github.com/cubewise-code/arc-issues/issues/186#issuecomment-442513021 but I think it was missed

**To Reproduce**
1. Press ctrl+space
2. Try to find the functions described above.

**Expected behavior**
All TM1 functions have to be visible in intellisense.

**Desktop (please complete the following information):**
Arc version 1.3.0
TM1 version 11.4.0.21
Browser Chrome / Firefox / Edge

**Comment by gpool21** [comment]
Hi @RaduCantor ,
Yes it looks like we missed this one - will handle additional functions ElementAttrPutS and ElementAttrPutN as part of the original request.

**Comment by gpool21** [comment]
#186
