### ISSUE TITLE
ER: Rule Editor. Drag & Drop dimensions into rule.

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#33]
In the Rule editor there is a list of dimensions in the cube with a hyperlink to the hierarchy editor for each dimension. It would be a useful shortcut for developers to be able to **drag** the dimensions into the rule editor to create a !dimension reference at the drop point.
![image](https://user-images.githubusercontent.com/29408388/38097949-01264270-3377-11e8-902d-40dbafc58328.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram, 

We are trying to make it so you don't have to use the mouse, we will add the !DimensionName to the top of the auto-complete instead. Closing this issue.
