### ISSUE TITLE
Arc v1.3.0: Result list of filter: text not visible

### ISSUE THREAD

**Issue by OlafFranke** [cubewise-code/arc-issues#338]
**Describe the bug**
If inserting some substring into the the text box above the objects tree gives a result list with items which have unvisible text: see screenshot (1)

Work around: You can only click to the icon on the left side; than the text becomes visible: see screenshot (2)

**To Reproduce**
1. Open arc and login
2. Click on filter text box and insert a substring of some object
3. See error

**Expected behavior**
All items are visible.

**Screenshots**

(1)  ![image](https://user-images.githubusercontent.com/44433920/49822821-7d053500-fd7e-11e8-8371-a5cdb8545cae.png)

(2) ![image](https://user-images.githubusercontent.com/44433920/49823091-2b10df00-fd7f-11e8-8ad6-eb71ece0f265.png)

**Desktop**
 - TM1 Version: 11.3
 - Browser:  Chrome Version:  71.0.3578.80
 - Arc Version: 1.3.0
 - Windows Verssion: Server 2016 Standard

**Additional context**
If I change back to 1.2.1 it works fully.

**Comment by cubewise-tryan** [comment]
Hi @OlafFranke,

I can repeat this, it looks fine in my tests, see below. There seems to be special characters in the names. Can you provide some sample names to see if that is the issue.

![image](https://user-images.githubusercontent.com/22929868/49921447-a7cbc680-ff01-11e8-9abf-b99b1b4242a4.png)

**Comment by OlafFranke** [comment]
Hi Tryan,
this is the result on the same machine, using previous arc version 1.2.1:
![image](https://user-images.githubusercontent.com/44433920/49953009-7fda6400-fefd-11e8-931c-d138adb339f3.png)

Wich special characters you mean? We using all characters which are usable in file names excluding German Umlaute(öüäÖÜÄß) and such like: §^°!$
In common only ASCII characters, no UTF-8.
Next what I will do is to install all Service Packs left on MS Windows 2016 Standard.

**Comment by OlafFranke** [comment]
Further - on "Microsoft Windows Server 2012 R2 Standard" the problem doesn't appear, it works with 1.3.0.

**Comment by OlafFranke** [comment]
Solution: I have deleted all browser data in Google Chrome - **now it works**.

**Comment by cubewise-tryan** [comment]
Hi @OlafFranke,

Thanks, it seems like some of the HTML template was cached. We will look into fixing that so it doesn't occur again.
