### ISSUE TITLE
Arc v1.3.0: Execute Process Button does not react

### ISSUE THREAD

**Issue by OlafFranke** [cubewise-code/arc-issues#339]
**Describe the bug**
If selecting a Process and intend to run it with "Ececute Process" functionality nothing will happen.

**To Reproduce**
1. Select a Process
2. Click on 'Lightning' Button
3. Click on 'Execute' Button
4. See error / process doesn't start.

**Expected behavior**
Process starts.

**Screenshots**
![image](https://user-images.githubusercontent.com/44433920/49824701-f56df500-fd82-11e8-81d6-21cae03f4e3a.png)

**Desktop**
- TM1 Version: 11.3
- Browser: Chrome Version: 71.0.3578.80
- Arc Version: 1.3.0
- MS Windows Version: Server 2016 Standard

**Additional context**
I changed arc version back to 1.2.1 - it works again.

**Comment by cubewise-tryan** [comment]
Hi @OlafFranke,

It is working fine for me, can you check the Developer Console in Chrome. Press F12 and try again. Post any errors so we can take a closer look.

**Comment by OlafFranke** [comment]
I think it has something to do with old data stored in Google Chrome.
**Solution:** I have deleted all browser data in Google Chrome - **now it works**.

**Comment by cubewise-tryan** [comment]
Thanks for the update.
