### ISSUE TITLE
Process saved without any error prompt on 10.2.2 FP4

### ISSUE THREAD

**Issue by winsonlee8** [cubewise-code/arc-issues#344]
**Describe the bug**
I have a variable "vTest" in the process which is not defined.  When i press on the save button ARC did not prompt that variable "vTest" is not defined. This only happens when used on TM1 10.2.20400.80.
When it is used with PA 2.0.5, it is working as expected.

**To Reproduce**
1) Having a statement CellGetN(1, cDestCube, vTest, vYear, vMeasure) in Data tab.
2) Click on the save button.
3) Process saved without any error.
4) When the process runs, the error "Variable "vtest" is undefined" is log on tm1server.log

**Expected behavior**
1) I should get a prompt indicating that error "Variable "vTest" is undefined" when the process is saved.

**Screenshots**

**Desktop (please complete the following information):**
 - TM1 Version: 10.2.20400.80.
 - Browser Chrome
 - Arc Version 1.3.0

**Additional context**

**Comment by lotsaram** [comment]
This is a deficiency in the Rest API not in Arc. In this version the API doesn't provide a method to test a process only to post it.

**Comment by winsonlee8** [comment]
Do you know which version onwards the REST API provides a method to test a process ?

**Comment by cubewise-tryan** [comment]
Hi @winsonlee8,

@lotsaram is correct, you need to be using TM1 11 or later. Although some things work on 10.2.2 we don't support that version because of the missing parts in the REST API.
