### ISSUE TITLE
Error Log is empty when Arc cannot start because the port is not available

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#37]
Hi,

TM1 version: 2.0.3
Arc: 0.9.2

If Arc is already running by another user on the server, if you double click on Arc.exe, Arc will not be able to start because the port is already being used. 

The issue is that arc.log does not say why Arc is not able to start.

To understand why Arc cannot start, you have run it using a command line and you will see that the port is not available:

![image](https://user-images.githubusercontent.com/25290041/38233646-99dfe74c-375e-11e8-89e3-137dc169b527.png)

Would it be possible to add a similar error message in the arc.log when Arc cannot start because the port is not available?

Cheers,

Vincent

**Comment by cubewise-tryan** [comment]
This has been added to the arc.log but it is highly recommended that you run Arc either as a service or with a system account. Running it as an application should only happen on a desktop or when testing.
