### ISSUE TITLE
improve toggle comment functionality

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#4]
At the moment the toggle comment functionality is a true toggle. However, as code blocks can frequently have comments interspersed explaining the following section of code the current functionality would be much improved if the comment/uncomment action **for all lines in the selection** was deduced based on the first line rather than evaluated line-by-line. For the action being "comment" any lines already being commented would simply have an additional # character applied as the first character on the line.

e.g. block of code is selected
![image](https://user-images.githubusercontent.com/29408388/37656055-3dc77e60-2c47-11e8-9254-7c719264c2f0.png)
Currently if toggle comment is performed we get the following result. Code is commented AND comments are uncommented. Resulting in code that will not compile. This is the result.
![image](https://user-images.githubusercontent.com/29408388/37656143-7d8a12b0-2c47-11e8-8463-f6884f028b84.png)
Whereas this is what should happen.
![image](https://user-images.githubusercontent.com/29408388/37656238-c7c9b010-2c47-11e8-87b0-632a298a1477.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram, 

This will be in the next version.
