### ISSUE TITLE
Debugger: Step Over does a Step In

### ISSUE THREAD

**Issue by RRicafranca** [cubewise-code/arc-issues#47]
This may have been a previously bug that was fixed, but has reappeared in v0.9.3.

When in debug mode and on an ExecuteProcess command, the Step Over button incorrectly does a Step In.

![image](https://user-images.githubusercontent.com/37824482/38386358-6c9eccf0-38e2-11e8-94cf-d1331b0b2956.png)

![image](https://user-images.githubusercontent.com/37824482/38386370-74ddc27c-38e2-11e8-8c01-4f753287b7a3.png)

Arc Version: 0.9.3
TM1 Version: 11.1.00004.3

**Comment by cubewise-tryan** [comment]
Hi @RRicafranca,

This is actually caused by a bug in the REST API that we need to work around, we will add some more logic so it works when ExecuteProcess is on multiple lines.
