### ISSUE TITLE
Threads Plugin: Cancel button not working

### ISSUE THREAD

**Issue by RRicafranca** [cubewise-code/arc-issues#48]
When trying to cancel threads related to a previous debugging session, the cancel button in the Threads plugin does not seem to work.

![image](https://user-images.githubusercontent.com/37824482/38386712-915e6ec8-38e3-11e8-86a0-9dbd2f785f86.png)

Not sure if this is a bug or a limitation.

I am able to cancel the threads quickly and easily using Pulse:

![image](https://user-images.githubusercontent.com/37824482/38386769-cb5f28ba-38e3-11e8-8437-8cfcfa613cb6.png)
![image](https://user-images.githubusercontent.com/37824482/38386799-df0f1aaa-38e3-11e8-9507-35926599d5fe.png)

**Comment by cubewise-tryan** [comment]
Hi @RRicafranca ,

This is working OK for me, it looks like the cancel button is grayed out. The Threads page is actually a plugin so it might be that an old version is cached in the browser. Try clearing the cache.

If that doesn't work check out the plugin code in \plugins\threads\plugin.js, the key bit of logic is `item.canCancel = item.State != "Idle"`. This only enables the Cancel button when the Thread is not Idle.

**Comment by RRicafranca** [comment]
Thanks Tim.

Hmm... interesting that it is working for you.

After clearing the cache and cookies, I am still experiencing this. I tried both Chrome and IE. 
It will still cancel via Pulse, but not via the plugin.


![image](https://user-images.githubusercontent.com/37824482/38399868-f20dbd1e-391a-11e8-9a18-9aac4309ccf8.png)
![image](https://user-images.githubusercontent.com/37824482/38399902-2e20d7b4-391b-11e8-84a5-5e1be2c97fd1.png)


Also tried to run some other processes, and when other threads are in a Run state, the buttons still appear to be grayed out.

![image](https://user-images.githubusercontent.com/37824482/38400005-d94df2de-391b-11e8-8880-21448372dfa8.png)

I'll play around with it some more. Thanks.

**Comment by cubewise-tryan** [comment]
Which browser are you using?

**Comment by RRicafranca** [comment]
I've tried it on Chrome and Internet Explorer...  the same behavior in both.

**Comment by cubewise-tryan** [comment]
This issue can't be replicated, closing until there is more information
