### ISSUE TITLE
Add refresh available dimensions button to create cube dialog

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#5]
It would be nice to have a refresh list of dimensions button in ‘Create Cube’ dialog (like in Architect new cube dialog). E.g. to cover the use case where the developer almost created the cube and then realized that they forgot to create a measure dimension.
![image](https://user-images.githubusercontent.com/29408388/37656715-1f0efe74-2c49-11e8-8dad-0aa98e5cff3b.png)

**Comment by saylett** [comment]
Slight addition to this would be the ability to toggle control objects from this UI rather than going all the way out to the main page to toggle.
