### ISSUE TITLE
Process Clone saves the existing process then SaveAs to new process

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#51]
Arc 0.9.3
Commonly an existing process is opened with the intention of using that process as a template for a new process and then doing a SaveAs/Clone to create the new process. However, as developers are only human we often forget to do the Clone immediately and make several edits BEFORE clicking Clone in Arc.

In this scenario the current behaviour in Arc is pretty undesirable as Arc will save the current process **without warning or notification** and THEN clone into the new process. _**What should happen**_ is that the old process is not saved and remains unchanged. This is expected behaviour that users have from using pretty much any other software. 

Depending on what sort of edits a developer has done before clicking Clone and whether they realise at all that the original process is changed in the background the way Arc handles this currently could have some quite nasty consequences.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram ,

That is not how it works, cloning a process doesn't save the existing process it takes a copy of the current process (including edits) and creates a new one. The original process is left in the unsaved state.

**Comment by lotsaram** [comment]
I will check it again and confirm but I am pretty sure I had this behaviour

**Comment by lotsaram** [comment]
Hi @cubewise-tryan it seems we are both right.
Yes the behaviour of Arc is correct. The process that is being cloned doesn't get saved first and the in-session changes are moved to the new cloned process.
However there is still a bug but it is different (and less harmful). Arc gives an incorrect notification that the process being cloned from is saved. This is the first action that happens after clicking Clone and entering the name for the new process. This notification shows while the original process is still the active tab with focus.
![image](https://user-images.githubusercontent.com/29408388/38538887-046f2474-3c96-11e8-83c0-0b3cdef19a9c.png)
After the new process is created the "saved" status indicator is still present on the old process but the Save changes before closing is still (correctly) presented when closing the tab. If the user selects discard then no unwanted changes are made to the process that was cloned.
![image](https://user-images.githubusercontent.com/29408388/38538947-4c032f2e-3c96-11e8-96f6-8ed3c4de459a.png)

I think all that is required to fix and remove the confusion is that the saved indicator shouldn't be displayed.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

I realised that as well, next version will say "**Cloned**" instead of "**Saved**"
