### ISSUE TITLE
Dimension subset All is not available as a TI data source

### ISSUE THREAD

**Issue by PiotrRajtar** [cubewise-code/arc-issues#53]
When using a dimension subset as data source in Architect, it is always possible to select a system subset called "All", whereas in Arc it is currently not possible to preview/create a variable if a dimension has no subsets.

![image](https://user-images.githubusercontent.com/32559614/38539969-9b7f2ab6-3cdd-11e8-87eb-4f931c668f1b.png)

Arc 0.9.3 @ PAL 2.0.4

**Comment by cubewise-tryan** [comment]
Hi @PiotrRajtar,

This has been added although the preview doesn't work as the REST API doesn't recognise the All subset.
