### ISSUE TITLE
Rules editor: Concatenated string is not highlighted

### ISSUE THREAD

**Issue by PiotrRajtar** [cubewise-code/arc-issues#55]
When concatenating a !dimensionName with a hard-coded string, it does not get highlighted:
![image](https://user-images.githubusercontent.com/32559614/38716207-d8079512-3f22-11e8-9a48-1ca3d0644715.png)

Arc 0.9.4 @ PAL 2.0.4

**Comment by cubewise-tryan** [comment]
Hi @PiotrRajtar,

It doesn't look like either the concatenated !Month or !Company is highlighted. Can you provide more details.

**Comment by PiotrRajtar** [comment]
Hi @cubewise-tryan,

Apparently in the editor theme that I am using (XCode) the !dimensionNames are not highlighted at all, but I am actually ok with this behaviour as I am not a huge fun of using italics for syntax highlighting.

So to make it more clear, this it what it looks like in XCode:
![image](https://user-images.githubusercontent.com/32559614/38785201-4bf033d2-4160-11e8-985e-229ff873799a.png)
And the same in Arc theme:
![image](https://user-images.githubusercontent.com/32559614/38785247-df5cf4f2-4160-11e8-8c73-0eff589892fd.png)

**Comment by cubewise-tryan** [comment]
Hi @PiotrRajtar,

We have added the pipe character as a delimiter to the dimension name so it will now look like this:

![image](https://user-images.githubusercontent.com/22929868/38785747-45fc334e-4166-11e8-8f7e-847db8654296.png)
