### ISSUE TITLE
Cube View size preventing use of Replace Variables

### ISSUE THREAD

**Issue by saylett** [cubewise-code/arc-issues#57]
When creating a new TI process with data source as a cube view, if the view is too large to display a preview, the 'Replace Variables' button is not available to click to pre-populate the variables tab.

![image](https://user-images.githubusercontent.com/37799830/38741079-024713ee-3f31-11e8-825c-6b8b9420ab43.png)

This is annoying when creating a temp view on a large cube, where typically I'd just save a blank view (with 'All' on each dim) and not try to preview. Is there any way the replace variables button could be used independently of the preview to pre-populate the variables in this case?

**Comment by lotsaram** [comment]
Agree with @saylett 
The reprieve should do a HEAD based on the entered number of preview rows. (Or else for VIEW type data source just do as the architect TI editor does and don't bother retrieving the view at all, just show 1 dummy record with the 1st element of each dimension in the cube)

**Comment by cubewise-tryan** [comment]
Hi @saylett,

This has been changed to limited the number of elements returned as well as the cells (these were already restricted).
