### ISSUE TITLE
Hierarchy Editor: dimension clone fails in 10.2.2 server

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#59]
Arc 0.9.3
TM1 10.2.207

For a pre v11 TM1 server dimension clone fails with message SaveAs not supported for resource type dimension. This is an upstream issue with the Rest API as opposed to an Arc bug. However, Arc should recognize the TM1 version doesn't support cloning dimension and disable the Clone button.
![image](https://user-images.githubusercontent.com/29408388/38742000-9d3302be-3f3b-11e8-9421-94127a67990a.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram, 

The function doesn't exist on 10.2.2 and we don't officially support that version. You should upgrade to v11 if you want to use that feature.
