### ISSUE TITLE
TI editor: Unable to fold If blocks

### ISSUE THREAD

**Issue by PiotrRajtar** [cubewise-code/arc-issues#60]
I cannot seem to fold If blocks in the TI editor anymore - it used to work fine until recently, and still works fine in rules.

Attempting to fold a block gives the following console error:
![image](https://user-images.githubusercontent.com/32559614/38847985-d7322580-4247-11e8-8426-dfd7e89814c2.png)

Arc 0.9.4
TM1 11.1.00000.30
Chrome 65.0.3325.181

**Comment by PiotrRajtar** [comment]
The same issue occurs for While and Region blocks.

**Comment by cubewise-tryan** [comment]
Hi @PiotrRajtar ,

This is working for me on the latest build, can you please test again on 0.9.5 when it comes out.

**Comment by PiotrRajtar** [comment]
Hi @cubewise-tryan,

The issue still occurs on 0.9.7, I tested it using Bedrock.Cube.Clone / Data:
![image](https://user-images.githubusercontent.com/32559614/40208223-eddb65c0-5a7b-11e8-8ebe-e01464d6636b.png)

**Comment by cubewise-tryan** [comment]
Hi @PiotrRajtar ,

Thanks, found the issue. It will be fixed in the next version.
