### ISSUE TITLE
Dimension Build Errors

### ISSUE THREAD

**Issue by alexandraesmith** [cubewise-code/arc-issues#61]
ARC Version: 0.9.4
TM1 Version: 10.2.20700.43
Browser: Chrome Version 65.0.3325.181 (Official Build) (64-bit)

Hi team 

I have come across the following issues when creating a new dimension in ARC

1) Unable to change element weight in dimension to -1.  Can change to any positive number ok

2) Unable to save dimension after receiving error message. This was during a test adding a string element to a consolidation. I received expected error, and removed element from consolidation, however was then unable to save dimension without error in usual way. (Attached are steps to replicate)

Let me know if any questions
Alex Smith

[ARC - Steps to replicate dimension build.docx](https://github.com/cubewise-code/arc-issues/files/1918205/ARC.-.Steps.to.replicate.dimension.build.docx)

**Comment by cubewise-tryan** [comment]
Hi @alexandraesmith ,

Can you please separate the issues so they can be tracked.

**Comment by alexandraesmith** [comment]
Hi Tim,

I have actually found a work around for the element weighting issue. If I type --1 (two hyphens) it will retain the negative number.

Alex
