### ISSUE TITLE
Editable snippets and syntax

### ISSUE THREAD

**Issue by gemerat1** [cubewise-code/arc-issues#62]
Hello, 

Arc is indeed a great tool, but it seems it is missing a function that was available in TI-Helper. 

In TI-Helper, we could customize the text files, and rewrite the existing functions and snippets. For example, in our organization, we have standardized the TI code by using UPPERCASE for the functions. And among other examples, we use the conversion of "space comma space" and "space parenthesis space". Or we prefix numeric variables with "VarN_" and string variables with "VarS_". So we edited the TI helper files to rewrite them using our own conventions.

Now, those resources are embedded in the ".exe" file and no longer accessible anymore. We know that we could find a workaround by creating our own plugins to get (to some extent) our own syntax of the snippets, but could it be that you consider in a future version to externalize those resources again, and store them in a series of text or XML files ? 

I would understand an answer like "no, because it is too deeply embedded in the auto-complete code".

Best regards,
Guillaume Emerat
SYNLAB.

**Comment by cubewise-tryan** [comment]
Hi @gemerat1,

The option to override the built in functions and snippets has been added and will be in 0.9.5. We will have details about how to do that in the release notes.

**Comment by lotsaram** [comment]
Hi @gemerat1 also see https://forum.cubewise.com/t/user-defined-snippets/1424/2
