### ISSUE TITLE
Arc displays incorrect logging timestamp if log4j.appender.S1.TimeZone=LOCAL

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#67]
Arc 0.9.4
In the built-in plugin Administration > ServerLogs Arc it looks like Arc is attempting to convert the timestamp of the tm1server.log entries from GMT to local time. However if the server message log is already logging in local time due to log4j.appender.S1.TimeZone=LOCAL parameter being set in tm1s-log.properties then Arc is actually compounding the Local time/GMT difference in the timestamp which it displays.

e.g. Server located at GMT + 2. Logs in server message log already recorded in local time
log entry directly from tm1server.log file
![image](https://user-images.githubusercontent.com/29408388/39058909-6a57447c-44bd-11e8-9434-a7c6947f6555.png)

In Arc the same log displays as 6:45 pm not 4:45 pm
![image](https://user-images.githubusercontent.com/29408388/39058953-8ca70ecc-44bd-11e8-9086-2a69c90adaeb.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram ,

Arc doesn't do any conversion but the JSON parser "interprets" date fields. The date time string that is provided by TM1 has an empty time zone (GMT) whether you have local time or not : `"TimeStamp": "2018-05-02T14:52:24.738Z"`

We will follow up with IBM as this seems to be a bug in the REST API.
