### ISSUE TITLE
Autorecalculate Feature

### ISSUE THREAD

**Issue by cubewise-plim** [cubewise-code/arc-issues#68]
TM1: 11.1.00000.30
Arc: 0.9.5
OS: Windows 10

Turning on/off the "Auto Calculate After Selection Changes" button seems to have no effect:

![image](https://user-images.githubusercontent.com/22946355/39556034-b44fd9e2-4ec0-11e8-9c8f-cd51cf2e694c.png)

Dragging dimensions into different axis does not update the cube view.

Had tried to clear the browser cache too.

Clicking on the flash icon (Execute) updates the view though.

**Comment by cubewise-tryan** [comment]
That is how it is designed, the dragging of hierarchies doesn't trigger the execution. Selecting one of the items in the drop downs is a trigger.
