### ISSUE TITLE
Formatting String cuts off

### ISSUE THREAD

**Issue by CWDavid** [cubewise-code/arc-issues#73]
It seems that ARC at the moment has a problem with the formatting string of TM1 cells. Arc is cutting the string off after the special character.

See attached screenshot with the value of the format attribute in Architect and ARC (0.9.6).

<img width="752" alt="screen shot 2018-05-03 at 5 49 17 pm" src="https://user-images.githubusercontent.com/38937638/39565336-e565d9e8-4efa-11e8-8b78-4b73c6afb10e.png">

**Comment by cubewise-tryan** [comment]
Hi @CWDavid ,

What is displayed is what is returned from the REST API so unfortunately it isn't something we can fix. We will contact IBM and see if that can be fixed in TM1.
