### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by CWDavid** [cubewise-code/arc-issues#74]
It would be good if ARC could check if the session has timed out and then block the user from any changes. 

I had a multiple situations, where I had the rule window open and changed code after some time of inactivity. The result is an error that the session timed out, but all the changes were lost. Ideally, ARC would store the changes internally if the session is timed out and then restore it from the internal storage when logged on. 

Alternatively, the rules editor could be deactivated if the session has times out.

**Comment by lotsaram** [comment]
@CWDavid I don't get this behaviour. For me it works not just after timeout but also for example if the instance has been restarted. Arc just re-authenticates in the background and gives a prompt to "re-do the last action" so just need to click save again. Do you have save credentials set to true?

**Comment by cubewise-tryan** [comment]
@CWDavid, 

I am not sure how the rule changes are lost? The page should be same state as before the timeout.

As @lotsaram says to help with session timeouts you should turn on **Store Credentials** on the About page. After a timeout you should just be able to re-execute the action. 

![image](https://user-images.githubusercontent.com/22929868/39567804-7885d04a-4f03-11e8-9826-69fba0bfe188.png)

**Comment by cubewise-tryan** [comment]
Hi @CWDavid ,

You are correct! The rules are being reloaded after login. This will be fixed in the next version.
