### ISSUE TITLE
Save as for Objects

### ISSUE THREAD

**Issue by CWDavid** [cubewise-code/arc-issues#75]
It would be good to have the option to save an object under a new name. Prime example are processes where saving it would mean a clone and deleted of the old process. 

Even better would be if some kind of refactoring kicks in and changes the reference of this process in other processes.

**Comment by cubewise-tryan** [comment]
Hi @CWDavid ,

You can already save a functions as using the Clone option. 

![image](https://user-images.githubusercontent.com/22929868/39568218-ce7a0056-4f04-11e8-891f-819c6fe51fcb.png)

**Comment by lotsaram** [comment]
I think @CWDavid is actually requesting a "Rename" feature which would be an enhancement if implemented. (e.g. wrap existing Clone with following background step to delete original object plus find/replace automatic background refactoring of existing dependencies)

**Comment by cubewise-tryan** [comment]
@lotsaram, we don't plan to add rename in addition to clone/save as.
