### ISSUE TITLE
Cannot resolve subset (rte 114)

### ISSUE THREAD

**Issue by nicknochnack** [cubewise-code/arc-issues#76]
Attempt to expand <i>All Months</i> roll up within cube viewer and error flag appears as follows:
![issue sc1](https://user-images.githubusercontent.com/5948934/39601896-d98ce6e0-4f66-11e8-9bc2-e5b1970f65c0.jpg)

When the view is opened the All Months rollup displays the fa-plus-square-o icon, it should however display fa-minus-square-o icon in order to replicate the original view. This might mean that the request being sent back might be trying to expand a rollup that is already expanded.
![issue sc2](https://user-images.githubusercontent.com/5948934/39601958-13083a28-4f67-11e8-8a5b-7947c6e10e2f.jpg)

Snapshot of console with bad request:
<img width="960" alt="console log" src="https://user-images.githubusercontent.com/5948934/39602086-7288cdb4-4f67-11e8-926a-9c06f85b6075.PNG">

Version of Arc:  0.9.6
Version of TM1: 11.1.00000.30
Browser and version: Chrome: 66.0.3359.139 (Official Build) (64-bit)

Step by step details of how to replicate the issue:
1. Open default view 
2. Expand all months rollup

**Comment by cubewise-tryan** [comment]
Duplicate #71
