### ISSUE TITLE
Can't access cube views when the TM1 objects in the menu are filtered

### ISSUE THREAD

**Issue by vviau** [cubewise-code/arc-issues#78]
Arc : 0.9.6
PAL : 2.0.3

Hi,

When the TM1 objects are filtered, I can click on the cube to get the rules but I can't access the views, the dropdown button is missing:
![image](https://user-images.githubusercontent.com/25290041/39610238-459aa266-4f92-11e8-8c3e-0748b328eee6.png)

From the menu when it is not filtered I can access the views:
![image](https://user-images.githubusercontent.com/25290041/39610245-5c21fcaa-4f92-11e8-9c38-2c7f2d37e12c.png)

Cheers,

Vincent

**Comment by cubewise-tryan** [comment]
Hi @vviau ,

The views/subset will now be added as a sub menu item.

![image](https://user-images.githubusercontent.com/22929868/39614053-e7707eb8-4faf-11e8-8e79-1fdae7b53250.png)
