### ISSUE TITLE
MDX View Error

### ISSUE THREAD

**Issue by cubewise-plim** [cubewise-code/arc-issues#81]
Hi,

What does the following error means when opening up an MDX View:

![image](https://user-images.githubusercontent.com/22946355/39611807-f8cd50ee-4f9d-11e8-9eb5-5a1ff4d1c8f8.png)

Below is the MDXView as returned by TM1:

`{
    "@odata.context": "../$metadata#Cubes('General%20Ledger')/Views/ibm.tm1.api.v1.MDXView/$entity",
    "@odata.etag": "W/\"88957\"",
    "@odata.type": "#ibm.tm1.api.v1.MDXView",
    "Name": "TempViewByMDX",
    "Attributes": {
        "Caption": "TempViewByMDX"
    },
    "MDX": "SELECT NON EMPTY {[Period].[Jan], [Period].[Feb], [Period].[Mar]} ON COLUMNS, NON EMPTY {[Account].AllMembers} ON ROWS FROM [General Ledger] where([Version].[Actual], [General Ledger Measure].[Amount], [Currency].[Local], [Region].[1], [Department].[1], [Year].[2012])"
}`

**Comment by cubewise-tryan** [comment]
There is an explanation of the view definition in the release notes: https://forum.cubewise.com/t/arc-for-tm1-release-0-9-5-0-9-6/1494
