### ISSUE TITLE
Deselecting Alias in subset editor

### ISSUE THREAD

**Issue by saylett** [cubewise-code/arc-issues#84]
I can't turn off an Alias of a dimension once enabled in the set editor;
![image](https://user-images.githubusercontent.com/37799830/39622854-9828b72c-4f8b-11e8-8900-dfdf6735d651.png)

I'm using TM1 10.2.2 FP5 & Arc v0.9.6

**Comment by cubewise-tryan** [comment]
Hi @saylett ,

Have you tried clicking the large cross beside the drop down?

**Comment by saylett** [comment]
... I have now @cubewise-tryan

**Comment by saylett** [comment]
Ah sorry - yes it does, not sure how I missed it!
