### ISSUE TITLE
Cell Formatting in Cube Viewer

### ISSUE THREAD

**Issue by saylett** [cubewise-code/arc-issues#85]
For a cube with values <1 Arc formats differently to Architect, and means I can't see the decimal places displayed as %'s. Is there a setting somewhere I'm missing?

Formatting is set in the Formatting attribute of the measures (on columns) to format as %'s, and this works in Architect.

Cells are rule generated - If I change to input cells the decimal places are visible, but only for those, a rule cell/consolidation alongside it still formats without DP (2nd screenshot)

![image](https://user-images.githubusercontent.com/37799830/39623849-e3d54994-4f8e-11e8-8901-c4fca51216bb.png)

![image](https://user-images.githubusercontent.com/37799830/39623922-290f9c9e-4f8f-11e8-9cbf-02d2b0a8105f.png)

TM1 10.2.2 FP5 & Arc v0.9.6

**Comment by lotsaram** [comment]
The way it works in architect/perspectives cube viewer based off the Format attribute is 
1st priority on column dimension
2nd priority on row dimension
3rd priority on title dimension(s) in stack order from right to left
4th priority on number format set for the view (for cells without any element with Format attribute defined)

**Comment by cubewise-tryan** [comment]
@saylett,

There is a fixed format for all values in Arc at the moment, we haven't added support for the TM1 formats.

**Comment by cubewise-tryan** [comment]
Hi @saylett,

Arc now takes the formatting from TM1 using the FormattedValue property on the cell object
