### ISSUE TITLE
Add Ctrl+A support to subset editor

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#86]
Arc 0.9.7
TM1 11.1.00004.3
Chrome 66

Currently multi-element select is click on element once to add to selection, click again to remove. So it is basically like holding the Ctrl key down in the old thick client we are used to.

Shift key for quick multi-selection of a range works well although it is a bit confusing at first with the different behaviour whether the element name is clicked versus the checkbox to the left.

When a subset editor frame is active it would be helpful if the Ctrl+A accelerator key combination did a select all of the elements in the subset editor. Current behaviour is we get a select all of the object names from the left-hand panel.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram ,

We don't want to encourage selecting all elements because it is very inefficient as each is member added as part of the MDX: `[Dim Name].[Hier Name].[Element Name]`

You should be using filters instead. If you want to select multiple items you can SHIFT and click.
