### ISSUE TITLE
Add delete key support to subset editor

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#88]
Arc 0.9.7
TM1 11.1.00004.3
Chrome 66

Currently when elements are in "selected" state in the subset editor they can only be removed by clicking the "Remove" button on the subset toolbar. It would be useful as well as intuitive to the user if the delete key could be used to remove the selected elements.

**Comment by cubewise-tryan** [comment]
Hi @lotsaram,

Can you please provide more details of what you are asking? You can click the checkbox to unselect an element or use the drop down list beside the Keep button.

**Comment by lotsaram** [comment]
Sorry I thought the request was obvious.
Rather than only being able to click the remove button why not be able to hit the delete key to also remove  the currently checked elements? Just like in the architect subset editor.
