### ISSUE TITLE
Variable List 

### ISSUE THREAD

**Issue by 4rtem** [cubewise-code/arc-issues#89]
Hi team, 

There is a long list of variables and object in TI Debugger, see the point and proposal on the scrrenshot.
v0.9.6

Thanks.
![image](https://user-images.githubusercontent.com/37865391/39631021-6348cfe4-4fb1-11e8-8fef-d2a6f6689d63.png)

**Comment by cubewise-tryan** [comment]
Hi @4rtem ,

You can already hide the locks by clicking on the Lock icon. You can also filter multiple variables by separating them with a space, each filter is a "contains" search so using an naming convention will reduce the number of filters required.

![image](https://user-images.githubusercontent.com/22929868/39657783-8f95d270-504e-11e8-96eb-d93051bfde41.png)

![image](https://user-images.githubusercontent.com/22929868/39657806-d833e8c8-504e-11e8-896a-210993a3217a.png)
