### ISSUE TITLE
Cube View not saving

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/arc-issues#90]
Hi

Created a new View via the Arc Cube Viewer.
The View name is created. But the view itself does not appear to be saved eg the rows and columns are not set.

Arc 0.97
Chrome 66.0.3359.139
TM1 11.2.00000.27

- Created a new View. Setting the desired rows and columns. Called the new view Default.
![1](https://user-images.githubusercontent.com/38934351/39678774-fd0c6804-51d5-11e8-84c3-5c50ed6aee68.PNG)

- Refreshed the navigation pane on the left, to see the new View listed under the cube.
- Noticed the new View name is listed in Arc (but does not exist in Architect even after refresh.)
- Opened the new View in Arc. But none of the view setting was saved ( eg. rows and columns not set ).

![2](https://user-images.githubusercontent.com/38934351/39678775-08907cce-51d6-11e8-8750-5549ea7775cc.PNG)

**Comment by cubewise-tryan** [comment]
Hi @cubewise-gng,

Arc only saves views in the MDX format which aren't accessible via Architect, you need to use PAX. See the details here:

https://code.cubewise.com/arc-docs/use-cube-viewer-in-arc

I am not sure why the view settings are not saved. Can you try again and see if you have the same issue.

**Comment by cubewise-tryan** [comment]
Hi @cubewise-gng ,

I can't repeat the issue so I will need some more information. Try using the Chrome Developer Tools (F12) to see if there is an error. It will show up in the Console tab in red.

You can also see the view returned from TM1 in the Network tab, filter the requests by typing "views" and then refresh the page, you will see the name of the view in the URL:

![image](https://user-images.githubusercontent.com/22929868/39680238-08861246-51e2-11e8-95cd-8ea015b40c55.png)

**Comment by cubewise-gng** [comment]
Hi @cubewise-tryan 

I've attached screenshots from Chome Developer Tools.
Here I am try to access the new view called "Test View"

![3](https://user-images.githubusercontent.com/38934351/39680400-a9a4c9dc-51e3-11e8-8a6f-735246f2c728.PNG)


![4](https://user-images.githubusercontent.com/38934351/39680401-ae03c78a-51e3-11e8-8f00-a114f82b992f.PNG)


![5](https://user-images.githubusercontent.com/38934351/39680404-b3f4db16-51e3-11e8-993f-1f6668902bbe.PNG)

**Comment by cubewise-tryan** [comment]
Hi @cubewise-gng ,

OK, thanks for that. It seems the REST API has been changed in 11.2. We can add an extra check to find what type of view it is before loading the details.
