### ISSUE TITLE
Setting Max Rows on Cube Viewer

### ISSUE THREAD

**Issue by cubewise-plim** [cubewise-code/arc-issues#91]
Arc: 0.9.7

Hi,

I might have missed out on something, but after setting the max rows on the Cube Viewer, I cannot seem to scroll or view the next sets of rows:

![image](https://user-images.githubusercontent.com/22946355/39680774-bf7166e0-51e7-11e8-84f2-c90894c5093e.png)

I tried scrolling via mouse but the rows are not moving. Expand and collapse is working fine and is showing the rest of the elements but still keeping the 10 row limit everytime. 

--
Paul

**Comment by cubewise-tryan** [comment]
Hi Paul,

It is a fixed limit, you can't scroll to anymore rows.
