### ISSUE TITLE
Search box populates with username when opening a process

### ISSUE THREAD

**Issue by lbrowncubewise** [cubewise-code/arc-issues#92]
I am having an issue on 0.9.6 where when I open a process the username of the connection keeping being populated into the search box, is this a known issue?

![image](https://user-images.githubusercontent.com/35220689/39744885-93eb69ba-529d-11e8-8d89-eff6d489e182.png)

**Comment by cubewise-tryan** [comment]
Hi @lbrowncubewise ,

The yellow background indicates that is Chrome that is filling out that detail, you must have it stored in the form filling settings in the browser. Try removing it in there.

**Comment by cubewise-tryan** [comment]
Hi @lbrowncubewise ,

Any update on this issue? Did you manage to clear it using the browser?

**Comment by lbrowncubewise** [comment]
@cubewise-tryan yep this has fixed my problem, thanks for your help.
