### ISSUE TITLE
Code colorization for new Hierarchy functions

### ISSUE THREAD

**Issue by lotsaram** [cubewise-code/arc-issues#93]
Arc 0.9.7
TM1 11.1.00004
Chrome

The auto-complete recognizes the new hierarchy aware TI functions but the code color formatting doesn't.
Here is an example of equivalent code using old vs new functions
![image](https://user-images.githubusercontent.com/29408388/39759211-5fe3abde-52d2-11e8-9ed4-b1f50758b426.png)

**Comment by cubewise-tryan** [comment]
Hi @lotsaram ,

Thanks, we will sort that out. At the moment the colourisation is separate to the function list, we will merge the two so they are always in sync.
