### ISSUE TITLE
Rules Editor - Regions not collapsing

### ISSUE THREAD

**Issue by Sneb85** [cubewise-code/arc-issues#94]
Arc Version: 0.9.7
TM1 Version: PA 2.0.3/11.1.00004.3
Browser: Google Chrome - Version 66.0.3359.139 (Official Build) (64-bit)

I'm using the #Region and #EndRegion tags in the Rules editor. The regions aren't collapsing at all.

This issue existed in 0.9.4 but was fixed in 0.9.6 but it's happening again in 0.9.7

**Comment by cubewise-tryan** [comment]
Hi @Sneb85 ,

We need some more information as it works in samples I am using. It will probably having something to do with the content between the region tags so if you can try to isolate what is causing the issue that would be be a great help.

**Comment by Sneb85** [comment]
Hi @cubewise-tryan 

I have attached the Rules file.

Hope this makes it easier for you to debug.
[General Ledger.txt](https://github.com/cubewise-code/arc-issues/files/2011150/General.Ledger.txt)

**Comment by cubewise-tryan** [comment]
Hi @Sneb85,

Your rule file works OK for me on the latest version when I paste the content, I can't save the rule file as I don't have the model. 

Can you try clearing your cache in the browser and trying again. If it doesn't work please check to see if there are errors in the Chrome Console by pressing F12.

**Comment by cubewise-tryan** [comment]
Hi @Sneb85 ,

Thanks, found the issue. It will be fixed in the next version.
