### ISSUE TITLE
Selected word functions

### ISSUE THREAD

**Issue by saylett** [cubewise-code/arc-issues#95]
When selecting a word in the editor, and it highlights the multiple instances of that word, I think it would be super useful to be able to easily cycle to the next/last instance of the word, either through a button/UI addition or keyboard shortcut

**Comment by cubewise-tryan** [comment]
Hi @saylett,

That is a built-in feature of the editor so is difficult to change. You can move between words using the Find dialog (Ctrl-F) and the {ENTER} key.
