### ISSUE TITLE
Copy variable result

### ISSUE THREAD

**Issue by psegal** [cubewise-code/arc-issues#96]
It would be useful to be able to copy the results of a variable in the debug window for testing, rather than having to write an asciioutput. I can't see a way of doing this currently, although entirely possible I'm missing something.

![image](https://user-images.githubusercontent.com/27949728/40109203-c7446ce6-58f4-11e8-8445-9a98947acb7d.png)

Firefox 60.0 (64-bit)

**Comment by cubewise-tryan** [comment]
Hi @psegal ,

Do you mean copy the "Value" as seen on the right hand side: `Powershell.exe send-mailmessage...`

**Comment by psegal** [comment]
Hi @cubewise-tryan ,

Yes, exactly.

**Comment by cubewise-tryan** [comment]
Hi @psegal,

This has been fixed and will be in the next version. The problem was the text was refreshed every second causing the selected text to be unselected.
